### ISSUE TITLE
Migrate from from deprecated test runner for integrations tests

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#1049]
**Is your feature request related to a problem? Please describe.**

The test runner for the current integration tests needs to be replaced. See here for the details: <https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode>

**Describe the solution you'd like**

- Remove ` "vscode": "^1.1.37"` from `packages/zowe-explorer/package.json`
- Remove these three files that refer to the outdated `vscode/lib/testrunner`:
  - `packages/zowe-explorer/__tests__/__integration__/index.ts`
  - `packages/zowe-explorer/__tests__/__theia__/index.ts`
  - `packages/zowe-explorer/__tests__/__unit__/index.ts`
- Follow the instructions above to create new test runners

**Comment by phaumer** [comment]
@lauren-li @zFernand0 fyi.

**Comment by lauren-li** [comment]
Here is a branch with a preliminary working upgrade of the test runner: https://github.com/zowe/vscode-extension-for-zowe/tree/update-testrunner

- The integration tests are able to run with the same results as in `master` branch, and I am able to set breakpoints in them.
- Unit tests are all able to run and pass, and I am able to set breakpoints in them. Although I updated the `index.ts` file and added a `runTest.ts` file in the `__tests__/__unit__` folder per the migration instructions, I'm not sure if these are necessary. Zowe Explorer's unit tests run using Jest, while the test runner specifies Mocha. The unit tests seem to behave the same, even if I delete the unit tests' `index.ts` and `runTest.ts` files.

Some things to note:
- I cannot get the Theia tests to run in my branch, but I also cannot get them to run on `master` branch. Most (or all) of the Theia tests seem to fail in both branches with the error: `Uncaught Error: Server terminated early with status 1`
- I did not remove the `vscode` dependency, since doing so seems to have the following effects:
  - `"@types/vscode": "^1.43.0"` seems to make VS Code's `EventEmitter.fire()` function have a required `data` parameter. Previously, that parameter was optional. This means we will need to add in an argument for the `refresh()` function in zowe-explorer's `src/abstract/ZoweTreeProvider.ts` file. I'm not sure if that's something we want to do as part of this issue or a separate issue. 
  - If switching to `@types/vscode`, I need to build zowe-explorer-api into a local `.tgz` file and use that instead of the version number in zowe-explorer's `package.json` reference to `@zowe/zowe-explorer-api`. Otherwise, many zowe-explorer properties show as undefined. For some reason, I don't get this problem when leaving `vscode` in place.

**Comment by crawr** [comment]
For the `fire()` command, I found this: [Event Emitter definition hint](https://code.visualstudio.com/updates/v1_45#_strict-null-fix-for-eventemitter) from vscode. The suggestion is to use `new EventEmitter<void>` instead of `<undefined>`

**Comment by lauren-li** [comment]
> For the `fire()` command, I found this: [Event Emitter definition hint](https://code.visualstudio.com/updates/v1_45#_strict-null-fix-for-eventemitter) from vscode. The suggestion is to use `new EventEmitter<void>` instead of `<undefined>`

Thanks @crawr for finding this hint! I replaced `undefined` with `void` in the `EventEmitter`, and it seems to work alright (both in manual and automated testing). I tested manually by adding sessions and also clicking the tree's "Refresh" button.

Thanks also to @phaumer for your advice on avoiding build errors when removing the `vscode` dependency!

**Comment by lauren-li** [comment]
I removed the `vscode` dependency, and added `mocha 4` per the migration guide. Since I was already making changes there, I went ahead and moved the `mocha` dev dependencies from the `zowe-explorer` package level to the top monorepo level, in case we want to use it for other packages in the future.
- **Note:** If you are testing the `update-testrunner` branch, you should delete your `node_modules` folder (I deleted mine at both the top level and under `packages/zowe-explorer`), and then re-run `yarn` at the top level. (You may have to restart VS Code to get rid of "errors" after doing this.)

After discussion with the Zowe Explorer squad, I also removed `index.ts` and `runTest.ts` from zowe-explorer's `__tests__/__unit__` folder, as our unit tests appear to only use Jest, while the test runner script specifies Mocha. Thanks especially to @zFernand0 and @Alexandru-Dumitru for your input on this! Like I mentioned in my earlier comment, I can still run unit tests fine from the command line and from VS Code's Debugger pane, and can still use breakpoints with these files absent. Per the discussion, it does not sound like this will impact automation pipelines, either.
