### ISSUE TITLE
Review and change the context menu items for clarity and consistency

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1052]
**Is your feature request related to a problem? Please describe.**

A discussion with a number of users of Zowe Explorer yielded several comments regarding items in the context menu. Specifically, the parentheses next to "allocate like" should say "New data set with same attributes" and at the bottom, we should just have "Delete", not "Delete PDS" (or whatever the case may be). 

These were just a couple of suggestions, and I think the squad should have a discussion about this. Also, we'll await John's feedback. 

**Describe the solution you'd like**

Let's have a discussion as a squad and agree on the terminology, with input from UX folks.

**Describe alternatives you've considered**

**Comment by crawr** [comment]
I just want to point out that the grouping and ordering of the context menu items are arranged to match what VS Code recommends for its explorer context menu: https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups
This was discussed in issue #347 and subsequently fixed in PR #834 

Also, regarding menu name changes, if any, I would suggest addressing them within the open PR #957 as they are related.

**Comment by jelaplan** [comment]
@crawr That VS Code org system seems like a good way to group and bring consistency. I don't want to disparage the work you and Lauren did. I think that what Zach has pointed out is that Delete PDS might be more concise, accurate, and in keeping with other changes if it were shortened to Delete. Rename used to be Rename Data Set. And referring to a PDS might not be accurate if the it were a PDSE or other format. 

WRT to the New File vs. New Data Set, the argument was made that the language is iconsistent and inacurate. It is a data set and not a file. The origin was in communicting with people who are new to Mainframe and more familiar with windows, unix etc. than mainframe. But, it isn't maybe so effetive to do it for a single command when broadly Zowe Explorer deals with Mainframe jargon and concepts. 

I tried to assign the VS Code categories to the current menu items. It is easier said than done and people may well disagree with my attempt. I do think that Allocate Like and Create New Member are closely related since they are both about creating a new item. Maybe the positioning of Allocate Like was based on the idea that we are copying the Data Set arguments and pasting them into a new Data Set.  

![image](https://user-images.githubusercontent.com/3207260/97251204-c9748500-17dd-11eb-9482-caee95a2a471.png)

**Comment by crawr** [comment]
@jelaplan Thanks for looking into the VSCode groupings.

I do think it is a great idea to go over our current menu and evaluate how we can improve it. Especially in light of the PR to remove most icons and move options to the context menu. 

This will be an easy technical fix but the groupings and wordings need a closer look, for sure.

**Comment by katelynienaber** [comment]
@jelaplan @crawr @zdmullen In the open PR [#957](https://github.com/zowe/vscode-extension-for-zowe/pull/957) I have made the name change to Allocate Like, and moved it in the menu.

I didn't change the names of Delete PDS, because it is handled differently in the PR...there, on a Data set, you see "Delete Data Set", and on a member it says "Delete Member".

The categorizations in the image I left alone, as that is a bigger change and I think maybe people will want to discuss it more.

Thanks guys for your input! Hopefully we can get it right and only change the layout for users one single time in a future release.
