### ISSUE TITLE
There is a strange error with too long data set names

### ISSUE THREAD

**Issue by nickImbirev** [zowe/vscode-extension-for-zowe#1083]
**Basically, the flow is very simple:**

1. Open the VS Code
2. Open the Zowe Explorer extension
3. Establish connection
4. Try to create a new dataset
5. Enter an any type, for example: ` Sequential `
6. Enter a very long name of the new dataset, like: ` HLQ.veryveryverylongname.data `

**AS IS:**
You will get the error like this:
```
Error encountered when creating data set! z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 8
rc:       860
reason:   2
message:  Dynamic allocation Error

Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 8
rc:       860
reason:   2
message:  Dynamic allocation Error
```
**TO BE:**
Such long names specification should not be available to submit, there should be adequate and understandable error.

**Environment:**
Zowe Extension version - v1.10.1
VS Code version - 1.51.1
OS - MacOS Catalina

**Comment by travatine** [comment]
Hi,

That error message is not particularly user friendly, perhaps it could include a link to 
the "z/OS MVS Programming: Authorized Assembler Services Guide" ( 
 https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.ieaa800/erc.htm ).

In this case the Guide says    " rc: 860  " means: 

![image](https://user-images.githubusercontent.com/17565183/103060646-d8ac5f00-45e3-11eb-8c48-2d728289ea6d.png)

and the Reason is the text unit in error.
Where '2' is referring to the 'dsname' text unit:

![image](https://user-images.githubusercontent.com/17565183/103060673-f8dc1e00-45e3-11eb-9e7b-bc2dd36f3d03.png)

The DSName text unit is described here:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.ieaa800/dsnam.htm

**Comment by katelynienaber** [comment]
@zdmullen Would it make sense to add some validation for DS names?

**Comment by jellypuno** [comment]
Validation for dataset name will not be handled by us. As per our strategy, this kind of validation should be done through z/OSMF APIs
