### ISSUE TITLE
When creating a new profile in ZE, I am prompted for port twice

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#1124]
When creating a new profile in ZE, I receive both of these prompts:
![image](https://user-images.githubusercontent.com/35504792/104058685-24edc680-51c2-11eb-8626-1b2eb08a6cfa.png)
![image](https://user-images.githubusercontent.com/35504792/104058704-2b7c3e00-51c2-11eb-9c16-8e90202bc4b7.png)

ZE should only prompt for port one time.

OS: Windows 10 & Ubuntu 16.04
Zowe Explorer Version: 1.11.1

**Comment by zdmullen** [comment]
If you enter a url with a host and port, you won't get the subsequent port dialog. That said, this seems to be a carryover from mirroring the behavior in the CLI. We'll talk in the squad about whether to remove the second one or not, because we would have to change the validation for the field I suppose (though perhaps that isn't much of an issue).

**Comment by jellypuno** [comment]
Adding to what @zdmullen said, the port dialog box is prompted just in case you forgot  to put the port in the URL dialog box. It still gives you that chance to put the port instead of going to edit. In my opinion, we shouldn't remove this port dialog box because it only appears if you failed to put a port. It makes sense to be prompted again because your profile will be incomplete.

**Comment by MikeBauerCA** [comment]
> If you enter a url with a host and port, you won't get the subsequent port dialog.

@zdmullen, that is not how it is working for me. 

I enter port 443 with the host and still get prompted for port again during initial profile creation (update doesn't share this issue; during update I only see it as a host:port combo).

I created the gif below to summarize my profile creation/update experience with Zowe Explorer:
![ZoweExplorerProfileCreationAndUpdate](https://user-images.githubusercontent.com/35504792/104194989-0ec54d80-53f0-11eb-93f3-9aa230c038df.gif)

**Comment by jellypuno** [comment]
now, I understand. It is because you are using port 443. Since we are using NodeJS URL function to handle the URL information, it converts port 443 to 0 that's why the port dialog box is displayed again. I cannot explain it but for some reason NodeJS is having a lot of validation/issues with 443. 

Reference: https://nodejs.org/api/url.html#url_url_port
```
// Default ports are automatically transformed to the empty string
// (HTTPS protocol's default port is 443)
myURL.port = '443';
console.log(myURL.port);
// Prints the empty string
console.log(myURL.href);
// Prints https://example.org/
```

For edit, there is a specific handling for port 443 that's why it is not happening.

**Comment by jellypuno** [comment]
https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/src/Profiles.ts#L399
