### ISSUE TITLE
Hide unusable profile context menu options

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#1125]
Some profiles support login in via the API Mediation Layer while others are direct to the service. For a profile that is direct to the service, the login context menu options should be hidden from the display.
![image](https://user-images.githubusercontent.com/35504792/104059444-5f0b9800-51c3-11eb-8dde-7f31b9050f4e.png)

If you click the button to login today, you receive this notification:
![image](https://user-images.githubusercontent.com/35504792/104059511-79457600-51c3-11eb-946e-c0ba1fcf49f3.png)

**Comment by crawr** [comment]
Yes, this was discussed during implementation of the login/logout process in ZE. At this time, there is no technical way for us to know whether the profile relies on SSO or not. Checking for the presence of a base profile is not enough, since I can use base profiles without relying on SSO tokens.

I believe there is/will be a new API ML endpoint that could help us with this: [https://github.com/zowe/api-layer/issues/873](https://github.com/zowe/api-layer/issues/873). This new endpoint will identify things like whether or not a service participates in SSO. 

Once the new endpoint is implemented, I believe we can call it during validation of profiles, and assign an SSO context value where appropriate. Then, we can just restrict the context menu to appear for profiles with this SSO context value.

**Comment by zdmullen** [comment]
This is to be researched once the API endpoint is available from the Mediation Layer.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
