### ISSUE TITLE
Refactor Zowe-specific calls to use Zowe Explorer API

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1139]
Bring Zowe-specific calls into the`zowe-explorer-api` package. For example, `zowe.IssueCommand`:
https://github.com/zowe/vscode-extension-for-zowe/blob/bcede696633a541df4bf236e6537424ba392747c/packages/zowe-explorer/src/command/MvsCommandHandler.ts#L227

(`zowe.IssueCommand` also shows up in `packages/zowe-explorer/src/job/actions.ts`.)

This change would allow Zowe Explorer extenders to also access the functionality.

**Comment by jellypuno** [comment]
Do you think this line should be change as well? https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/src/Profiles.ts#L530

**Comment by crawr** [comment]
probably linked to #1266

**Comment by JillieBeanSim** [comment]
Issue MVS Command is now available via the Zowe Explorer APIs
https://github.com/zowe/vscode-extension-for-zowe/blob/e67089692df3dd3c38520462a73c4f17c5cf53db/packages/zowe-explorer/src/command/MvsCommandHandler.ts#L136

I will create a PR for the changes done to the jobs actions.ts file since they are not using the APIs
