### ISSUE TITLE
Metal C development environment

### ISSUE THREAD

**Issue by CoderCoco** [zowe/vscode-extension-for-zowe#1155]
**Is your feature request related to a problem? Please describe.**

When developing Metal C in VS Code, the native C extension doesn't know how find `<metal.h>`.

**Describe the solution you'd like**

An environment provided by this extension or a brand new extension to assist with Metal C development. This could be something that assists you in finding where the header files are at on the mainframe and potentially setting up datasets to form a project of sorts. If we could have something that gets created and runs hello world that would be great.

**Describe alternatives you've considered**

To create all the datasets and JCL, I could do that manually but it was a tedious task for me. Took a few hours for me to get hello world working.
I could also pull down the header file for metal.h and then configure the VSC C extension to also use that.

**Additional context**

Wasn't sure where to open this issue, I feel like what I am asking for would be an extension to do Metal C development. I would find a lot of use out of such an extension.

**Comment by FALLAI-Denis** [comment]
Is the management of a programming language and the search for dependencies the responsibility of Zowe Explorer?
Wouldn't it be more the responsibility of a Code Editor?

**Comment by dkelosky** [comment]
You make a good point.  

I do a lot of metal C development though, and in each project, I need to pull down copies of z/OS specific metal C headers from USS locations and z/OS data sets.  I put them in a __chdr__ folder that I don't include with my build.  When the files are local, it helps with intellisense and symbol resolution.  

It might be nice if we could help pull these for users based on some configuration if it's possible, so that I don't need to keep downloading them for each project.

**Comment by jellypuno** [comment]
This will not be handled by Zowe Explorer but it could be handled by a different extension that deals with LSP.
