### ISSUE TITLE
Research: Handling of TSO commands

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1162]
**Is your feature request related to a problem? Please describe.**

I want to understand the previous behavior of the Issue TSO command and look into re-implementing it. I also want to get feedback from stakeholders on the expected behavior. Also, the extensibility of the commands and the API for it should be considered. 

This is discussed in issues #684 and #809. #875 as well. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jellypuno** [comment]
Just for info. I opened #1168 that is connected with issuing commands

**Comment by JillieBeanSim** [comment]
Trying to formulate a plan to address all the issues attached to this research.

- https://github.com/zowe/vscode-extension-for-zowe/issues/684
   ITso with a getTsoApi()  & IConsole with a getConsoleCommandApi() or we could have ICommand with getTsoApi() & getMvsCmdApi()
- https://github.com/zowe/vscode-extension-for-zowe/issues/809
   Update the `Ctrl+Shift+P` / `Cmd+Shift+P` with issue search to have both `Zowe: Issue TSO Command` & `Zowe: Issue MVS Command`
- https://github.com/zowe/vscode-extension-for-zowe/issues/875 & https://github.com/zowe/vscode-extension-for-zowe/issues/802
   Update the dialog to read `Create a New MVS Command` vs `Create a New Command` the right click menu item has already been addressed.
- https://github.com/zowe/vscode-extension-for-zowe/issues/1168
  address the issue with not prompting for credentials with profiles that don't have them stored vs showing a list of profiles

How does this plan look @jellypuno @zFernand0 @crawr ?

**Comment by JillieBeanSim** [comment]
I can address 809 then 875 & 802 in small PRs correcting the existing behavior to close those issues.
To correct 809 we could change the text in the `Zowe: Issue TSO Command` which is linked to issue console command to read `Zowe: Issue MVS Command`
To correct 875 & 802 we can update the dialog text

1168 can be addressed in it's own PR to fix the bug and have it prompt for creds.

We can then address 6804, bringing in TSO functionality and add it & Issue MVS Command into the API file and with that fix we will also add the TSO right click menu item and add it to the Zowe TSO command options with `Ctrl+Shift+P` / `Cmd+Shift+P`

**Comment by jellypuno** [comment]
Hey @JillieBeanSim, This looks good! So just to clarify:
1. If I do a right-click on my profile, the context menu will say `Issue MVS Command` and `Issue TSO Command`. 
2. If I do a `Ctrl+Shift+P / Cmd+Shift+P` , A dialog box will appear. I will need to select between `Issue MVS Command` and `Issue TSO Command`

Do you think it is good to re-use the approach for both scenario? Like I do a right-click > Click `Issue Command` > a dialog box will pop where I choose `Issue MVS Command` or `Issue TSO Command`. Then the same UX will be applied if I click `Ctrl+Shift+P / Cmd+Shift+P` . What do you think?

> #684
ITso with a getTsoApi() & IConsole with a getMvsCmdApi() or we could have ICommand with getTsoApi() & getMvsCmdApi() in the ZoweExplorerApi.ts

Which approach do you prefer here? I only understand the ICommand in ZoweExplorerApi.ts so that makes sense to me.

**Comment by JillieBeanSim** [comment]
> Hey @JillieBeanSim, This looks good! So just to clarify:
> 
> 1. If I do a right-click on my profile, the context menu will say `Issue MVS Command` and `Issue TSO Command`.
> 2. If I do a `Ctrl+Shift+P / Cmd+Shift+P` , A dialog box will appear. I will need to select between `Issue MVS Command` and `Issue TSO Command`
> 
> Do you think it is good to re-use the approach for both scenario? Like I do a right-click > Click `Issue Command` > a dialog box will pop where I choose `Issue MVS Command` or `Issue TSO Command`. Then the same UX will be applied if I click `Ctrl+Shift+P / Cmd+Shift+P` . What do you think?
> 
> > #684
> > ITso with a getTsoApi() & IConsole with a getMvsCmdApi() or we could have ICommand with getTsoApi() & getMvsCmdApi() in the ZoweExplorerApi.ts
> 
> Which approach do you prefer here? I only understand the ICommand in ZoweExplorerApi.ts so that makes sense to me.

Hey @jellypuno after reading the comments in the issues, it looked like having the separate approaches for `Ctrl+Shift+P` / `Cmd+Shift+P`  were more favorable and that's why I was leaning that way with the right click action as well https://github.com/zowe/vscode-extension-for-zowe/issues/809#issuecomment-644745764.  We can discuss this as a team if you would like before settling on one or the other.
For the API section, I agree to only have the one (ICommand) vs adding multiple since they will both deal with commands and if/when we bring in UNIX command support we could just add it there as well.

**Comment by JillieBeanSim** [comment]
suggestion from @katelynienaber:
- 1 command `Issue Command (MVS/TSO)` with the quick pick to choose which type and keyboard shortcuts like `Ctrl+Shift+M` for MVS Command and `Ctrl+Shift+T` for TSO commands

**Comment by JillieBeanSim** [comment]
Fun stuff!
![tso-command-wo-tso-profile](https://user-images.githubusercontent.com/49491949/112069408-25032e80-8b42-11eb-83d9-1d1107c07438.gif)

Still ironing a few things out but hey, Issuing TSO commands *woo hoo!*

I still need to get this action moved into the APIs so extenders can consume it & check for existing TSO profile to get the account number from if it exists.

Draft PR open if anyone wants to play around with it https://github.com/zowe/vscode-extension-for-zowe/pull/1245

**Comment by jellypuno** [comment]
good job @JillieBeanSim ! Looking forward to this feature 😄
