### ISSUE TITLE
Password issue: Incorrect credentials

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#1176]
**Describe the bug**

If I enter incorrect credentials, my profile is marked as `Unverified`, not `Invalid`.

**To Reproduce**

1. Disable validation on a profile without user/pass
2. Try to search with this profile
3. Enter an incorrect user or pass
4. See error `Cannot read property "getSessionNode" of null`...caused because profile should have a session, but it doesn't because it was not properly authenticated.

**Expected behavior**

If I enter bad credentials, my profile should be marked as `Invalid`.

**Comment by JillieBeanSim** [comment]
@katelynienaber this may have been fixed with https://github.com/zowe/vscode-extension-for-zowe/pull/1404 
When I follow your steps for recreation I don't get the invalid icon anymore
![image](https://user-images.githubusercontent.com/49491949/130070643-26507193-0036-47e3-990c-652912c02e81.png)

Could you retest the scenario and close this if fixed?

**Comment by katelynienaber** [comment]
This isn't happening any more, I am seeing the correct "Invalid credentials" message in the bottom corner. So I will close it.
