### ISSUE TITLE
Recall recently used searches/filters

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#118]
Each time Visual Studio Code is started, the user must enter their filter criteria for data sets, USS files, and jobs. It would be desirable to retain the previously set filters on subsequent startups. It would also be desirable to quickly recall recently used searches/filters.

**Comment by Colin-Stone** [comment]
Agreed that this feature should be part of GA 1.0

**Comment by Colin-Stone** [comment]
VSCode doesn't provide the level of widgets and components that are provided by Eclipse for example. I think this is because VSCode is lightweight and tries to keep things simplistic. Eclipse on the other hand is a much heavier weight environment. The problem is we have only two widgets to play with. An input dialog and a Picker dialog. No custom dialog or combination is available. Therefore I think our only option would be to provide a sequence of dialogs. The first will ask if the user wants to use a criteria from history and if not an input dialog. They work like this on what would be the new Jobs filter.   
![Screenshot 2019-07-25 at 12 43 32](https://user-images.githubusercontent.com/30794003/61872105-64472b00-aeda-11e9-8546-3c480b7dce70.png)
If the user selects a previous filter it is applied. However if they want to create new the following dialog replaces the picker one..
![Screenshot 2019-07-25 at 12 44 09](https://user-images.githubusercontent.com/30794003/61872106-64472b00-aeda-11e9-8f3f-a6f75b844a2b.png)
The user can then populate the filter as described in the image

**Comment by Colin-Stone** [comment]
When recalling history I propose keeping a list of the last 5 different searches. There is an option to have a list for each individual profile within USS/Job/Dataset but I think these would ideally be at the USS, Job or Dataset level instead. Any strong opinions?

**Comment by Colin-Stone** [comment]
https://github.com/zowe/vscode-extension-for-zowe/pull/247

**Comment by MikeBauerCA** [comment]
Nicely done! Feature to quickly recall recently used searches/filters available in 0.25.0 :)

Looks like #210 will cover the persistence request.
