### ISSUE TITLE
USS add ability to create folders and files on the root node

### ISSUE THREAD

**Issue by kristinochka** [zowe/vscode-extension-for-zowe#119]
When user adds a filter to view files in USS, they can only create files and folders on the child nodes, not on the very top node.

**Comment by Colin-Stone** [comment]
Consider in the context of https://github.com/zowe/vscode-extension-for-zowe/issues/106

**Comment by Colin-Stone** [comment]
Good thinking, instead of restructuring the tree with the multiple roots which is still under consideration lets provided this functionality now as it should be a simple implementation. The current "add file", "add directory" works relative to the currently selected location which is fine. So it should just be a case of recognizing that the user has specified the full path i.e. /u/myuser/newDir and pass that to the API which should function fine.

I think it would also be good to add the text which describes where the current single root is 
![image](https://user-images.githubusercontent.com/30794003/60158087-30e48400-97e8-11e9-98e9-178ae8b8740c.png)
