### ISSUE TITLE
Multi-selection support for all applicable functionalities

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1286]
Allow multi-selection of PDS members in the  dataset tree. This will allow the user to perform the following:
- Copy multiple PDS members to another PDS 
- Delete multiple PDS Member

This may involve UX

**Comment by katelynienaber** [comment]
Multi-delete of DS + members will be completed with this PR: https://github.com/zowe/vscode-extension-for-zowe/pull/1323

**Comment by jellypuno** [comment]
MVP: 
- Copy from PDS to PDS
- Process is done through context menu. PDS1: Right-click > Copy then PDS2: Right-click > Paste
- Research for Drag and Drop, if it is possible
- Questions:
   - What happens if there are duplicates? Pop a confirmation message? 
   -  Should we add a max number of members to copy? Research needed.

**Comment by katelynienaber** [comment]
Note: Drag and drop is not possible now, but may soon be available! [It's in the "proposed" API for VSCode](https://github.com/microsoft/vscode/blob/fa8ccff4d8c25128d9c34fff1a7e3113525147ba/src/vs/vscode.proposed.d.ts#L942), but not in the currently-released stable version.

I am not sure when it would be released into the stable version, but it is currently in the "feedback-gathering" phase. It can be tested out in any project by importing the Nightly build of VSCode's API. But we can't release an extension using that version of the API, because the Microsoft team considers it unstable :)

**Comment by jellypuno** [comment]
Drag and Drop is part of the Nov 2021 plan: https://github.com/microsoft/vscode/issues/136630
