### ISSUE TITLE
Implementation: Support working with project level config

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1287]
As a ZE user, I would like to use the team config stored in my single folder workspace.

Items to consider:
- What will happen if the user changes their current project folder? Can ZE capture the team config stored in that new project folder? 
- Can you use the `onDidChangeWorkspaceFolder` API to detect the event change and call `refreshAll`?
- If the answer to the previous question is no, can we configure the refresh button to trigger the Profile Manager initialization and change the project dir path?
- Handling of Persistent Data. What will happen if I switch folders and the profile doesn't exist in the config file in that context?

**Comment by IgorCATech** [comment]
Any doc impact here?

**Comment by crawr** [comment]
Research document: 
[Issue 1287_ Support working with project level config.docx](https://github.com/zowe/vscode-extension-for-zowe/files/6615976/Issue.1287_.Support.working.with.project.level.config.docx)

## Summary

### Context Switching
**Question:** What will happen if the user changes their current project folder? Can ZE capture the team config stored in that new project folder? 
**Answer:** Yes, based on VS Code’s `vscode.workspace.workspaceFolders` the ProfileInfo API can detect the `zowe.config.json` file in the current context

### VS Code event watcher 
**Question:** Can we use the `onDidChangeWorkspaceFolder` VSCode API to detect the event change and call `refreshAll`?
**Answer:** This is not the correct API for single-root workspaces. See [https://github.com/Microsoft/vscode/issues/61137#issuecomment-431868780](https://github.com/Microsoft/vscode/issues/61137#issuecomment-431868780)
We can use the `vscode.workspace.createFileSystemWatcher` API instead which will watch for existence of the `zowe.config.json` file

### Manual refresh
**Question:** How will the refresh happen when the context has been switched?
**Answer:** 
- Option 1: Call CLI Profile Manager initialization again when the user clicks the `RefreshAll` button
- Option 2: Ask user to manually reload VSCode once the file watcher detects a new project context

_This is an open question to the squad._

### Handling of Persistent Data
**Question:** What will happen if I switch folders and the profile doesn't exist in the config file in that context?
**Answer:** Since we are changing the tree when there is a change in context, the errors will only appear for non-existing Favorites. We have an existing error message for that.

### Use Cases
| Switch to:          | ProjectA w/ config | ProjectA w/o config  | ProjectB w/ config | ProjectB w/o config  |
|---------------------|--------------------|----------------------|--------------------|----------------------|
| Global              | ProjectA           | Global               | ProjectB           | Global               |
| ProjectA w/ config  | N/A                | N/A                  | ProjectB           | Global or old-school |
| ProjectA w/o config | N/A                | N/A                  | ProjectB           | Global or old-school |
| ProjectB w/ config  | ProjectA           | Global or old-school | N/A                | N/A                  |
| ProjectB w/o config | ProjectA           | Global or old-school | N/A                | N/A                  |
