### ISSUE TITLE
V1 Conformance - Create a best practice documentation for error handling

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1292]
As part of the conformance criteria, we would like Zowe Explorer to have a Best Practice Documenation on how to implement error handling.

V1 Conformance requirement is a documentation. In this document, we would like to advise extenders on how they are going to display their error message. 

My proposal is 
1. to use this format: `Extension Name` - `Error Message`
2. To throw a not implemented error for Zowe Explorer APIs that are not implemented in their extension

V2 requirement is an API: We would like to have an API that will allow users to call and pass their error message. It may still use the proposed format above. Additionally, we could implement error codes for better debugging (e.g. [APIML Error Codes](https://docs.zowe.org/v1-6-x/troubleshoot/troubleshoot-apiml.html))

**Comment by crawr** [comment]
Include a review of the error message strings we currently have

**Comment by katelynienaber** [comment]
Thoughts:
- From all functions, we should NOT be throwing errors. We should be returning some result type. This would force extenders (and us) to handle the errors, and we couldn't accidentally miss catching an exception, thereby crashing the app! I like this format (scroll down pls): https://benjaminjohnson.me/blog/typesafe-errors-in-typescript
- Alternatively, we could wrap the whole extension in an emergency try/catch block, and then we can be sure we won't accidentally crash the app. This seems like an easier solution **but I think it's a worse one long-term**. It's just a quick-and-dirty stop-gap measure. Errors should be dealt with when they occur, not later on when we are so far away from the source of the problem that we don't even know where it came from.

**Comment by katelynienaber** [comment]
![image](https://user-images.githubusercontent.com/58596139/117455119-27311900-af47-11eb-9cfc-9e5db340a434.png)

**Comment by crawr** [comment]
I like this idea of putting it in an API, usable for core ZE as well as extenders. 

Right now we are using the following in our code base:
- errorHandling utility: more for VS Code UI displays
- logs4jsconfig: mostly for debug logs
- ImperativeError class: we use this in a couple of locations to throw errors

I'm wondering if we are able to incorporate them in the API. I know that the ImperativeError is used by the Zowe Node SDK like in this example in the [List class](https://docs.zowe.org/stable/typedoc/classes/list.html). We follow the message format defined under logs4jsconfig.json, too, so we don't have to start from scratch there. 

I know for V1, we are just concerned about the error message format, but this is a good starting place for the work for V2.

**Comment by katelynienaber** [comment]
@crawr Some thoughts...

- errorHandling: Maybe we can pull out the code from this function which handles error 401 (reprompting of creds) and the messaging that's currently in this function could simply be passed to the API as the error message.
- logs4jsconfig: this is using the imperative logger, I only found it in relation to initializing this logger. I wrote the API logging function to use the imperative logger. So I think this should not change...
- ImperativeError: I think this could just be replaced by our logging function. We can use an ImperativeError in our function if we need to.

So yeah. Lmk what you think ^^'

**Comment by crawr** [comment]
Sounds reasonable to me! Thanks for looking into it

**Comment by katelynienaber** [comment]
@jellypuno I don't understand when this would occur: "To throw a not implemented error for Zowe Explorer APIs that are not implemented in their extension"

Why would there need to be an error if some API isn't implemented? If the extender doesn't use an API, they just wouldn't import it, right? Do you mean specific methods that aren't used in their extender, like we do [here](https://github.com/zowe/vscode-extension-for-zowe/blob/327396d2b1e231591fcfdb8f5cf510acfa0cd307/packages/zowe-explorer/src/dataset/DatasetTree.ts#L111)?

**Comment by jellypuno** [comment]
@katelynienaber Similar to what FTP ext is doing [here](https://github.com/zowe/vscode-extension-for-zowe/blob/8080ae14734eb9673b178687d92df94e203aad35/packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts#L200)

**Comment by katelynienaber** [comment]
**Tentative V1 Best Practices:** [Click here for doc](https://docs.google.com/document/d/e/2PACX-1vT4l_CUGgBVuMofIeX-0rgrDConfhdTDrEgEBvP8irzQ0VZlhsDh8Rd7quMmWQ-AbZgTGCz_FtyvaOc/pub)

**Comment by katelynienaber** [comment]
More thoughts after talking with @lauren-li ...

Test branch is [here](https://github.com/zowe/vscode-extension-for-zowe/tree/api-error-logger). Logger is [here](https://github.com/zowe/vscode-extension-for-zowe/blob/ea6ebcfe66389e857d523214877d955a44d5f308/packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts#L115). Example of use is [here](https://github.com/zowe/vscode-extension-for-zowe/blob/ea6ebcfe66389e857d523214877d955a44d5f308/packages/zowe-explorer/src/extension.ts#L95).

I tagged people I think can answer the questions. But ofc anyone can add to this as they like :)

## Questions for @JillieBeanSim:
- How would this API setup for the logger work with the cics extension? Specifically, the current WIP setup has a dependency on VSCode...

## Questions for @VitGottwald & @nickImbirev:
- We have a problem with [this function](https://github.com/zowe/vscode-extension-for-zowe/blob/ea6ebcfe66389e857d523214877d955a44d5f308/packages/zowe-explorer/src/utils/ProfilesUtils.ts#L83). It has a dependency on VSCode AND our profiles API. To solve this, can we create the basic logging functions as a base class & profiles prompting function as an extension of this base class? similar to `ZosmfCommonApi` & `ZosmfUssApi`. Then people could skip the import of the extended class if they don't want the profiles dependency...
- Error codes? How to tell which error we have, without doing something like `if (string.includes("I am an error")) { ...` ?

## Research needed:
- Can we get name of extension from `package.json` with VSCode's API? (In error messages, we must add identifying info about the extension name that caused the error)

## Conclusions
- The new logging API functions should not be in the `zowe-explorer-api/src/profiles` API folder, because they depend on VSCode. Maybe we can make some new file in the `tree` folder...
- Localization: Extenders should pass our logger localized strings. They would run localization themselves.
