### ISSUE TITLE
Create an Acceptance Criteria Doc for products what will be included in monorepo

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1294]
I would like to propose a squad level acceptance criteria in adding products in our monorepo. These are my questions:

1. Should we pattern our criteria in the OMP ruling for accepting incubator projects?
2. What is the acceptable state of the product before adding in the monorepo?
3. How do we ensure that there is a support added for that product?
4. What happens if the support leaves? Should we remove the product in the repo? What is the process for that removal?
5. Should the product be Zowe Explorer conformant before adding it in the monorepo?
6. Are we adding all products in the monorepo or just products part of the Zowe Core?

If you have more questions, comments, suggestions, please feel free to add it here.

**Comment by armstro** [comment]
I am not sure I understand the use of the term "product" in this context? It is not a commercial offering correct? We should be talking about open source (that might be used in a product - aka commercial offering). The topic of acceptance criteria for incubator is one the ZLC wants to take on in cooperation with the TSC. "Support" means committers and if there is not agreement on committers then we have a problem. At the moment the process we have is here https://github.com/zowe/zlc/blob/master/process/proposal_process.md and we are thinking it is not enough. Or we need to be clearer on the "promotion" to a squad - something I think the TSC should approve rather than ZLC or OMP

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
