### ISSUE TITLE
Determine where to document Zowe Explorer developer and extender information

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1329]
Open questions for the Zowe Explorer squad and squad leads:
1. When do we when do we use Wiki versus in-line MD git documentation? 
2. Where will we document the conformance documentation (e.g. the result of PR #1290 and issue #672)?

**Comment by jellypuno** [comment]
I don't mind if it is in wiki or docs but I prefer to put it under docs/extending/* folder so that if a user cloned the repo the docs can also be opened in the workspace. Maybe we can put a poll on slack regarding this one?

**Comment by crawr** [comment]
Per last week's scrum meeting (27-May) majority decided to document the information as MD files under the existing docs folder, instead of the Wiki. There will be two subfolders:
- `docs/extenders` for information extenders will need to refer to and adhere to as part of conformance and
- `docs/developer` for contributing guidelines within core ZE code

**Comment by lauren-li** [comment]
@crawr @jellypuno Is this resolved?

**Comment by zFernand0** [comment]
See wiki: 
- https://github.com/zowe/vscode-extension-for-zowe/wiki/Extending-Zowe-Explorer
