### ISSUE TITLE
Show the config file location

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1407]
As a Zowe Explorer user who uses the vNext version, I would like to see the location of the config file where my profile resides. It could be via tooltip or via context menu > Show Config Information. 

To do: Discuss the appropriate UX for this feature.

**Comment by zFernand0** [comment]
With the addition of the Team Configuration files, the Update and Delete actions behave in a similar way to "Show Config Info" since they will open the config file in the editor.

I'm proposing that (if possible) we go with a `Reveal in <Explorer/Finder>` 😋

**Comment by zFernand0** [comment]
@KutluOzel-b brought up a great question about this issue.
Do we really need another right click action for this ?

Since we already have many ways to access the Team Configuration profile, we believe it's ok to close this issue for now.
And if we need something similar to this, we can open a new issue 😋
