### ISSUE TITLE
Change context menus for multi-select

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#1428]
If multiple nodes are selected, the context menus should only show commands which support multi-select.

For example, delete is available for multiple nodes at once, but cancellation of jobs is not available. So Cancel Job should be hidden when multiple jobs are selected in the tree.

**Comment by zFernand0** [comment]
Please refer to 7f97adfeb2cdeecf7b93c994e56c9d01df45e6f2 for the latest code changes.
`git checkout 7f97adfeb2cdeecf7b93c994e56c9d01df45e6f2`

**Comment by KutluOzel-b** [comment]
Currently we are not allowing users to open multiple editor tabs at the same time. Is it intentional ? Considering selection of multiple files , allowing edit / pull from mainframe etc.. does not seems logical if we have no intention of allowing users to edit multiple files at the same time. 

My question is : I can't see any harm of allowing users to edit multiple files at the same time . Do you see any pitfalls in here ?

**Comment by zFernand0** [comment]
Personally, I don't see any harm in allowing such behavior. 😋
