### ISSUE TITLE
Issues with USS files having "same name", but different case

### ISSUE THREAD

**Issue by fswarbrick** [zowe/vscode-extension-for-zowe#1484]
**Describe the bug**

USS files in the same directory with file names that differ only in the "case" of one or more characters ("test" vs. "Test") are being treated within Zowe Explorer as "the same file" in some contexts.

**To Reproduce**

1. Create a USS file, for example "test".
2. Open the file and add some text.
3. Save the file.
4. Create another USS file, with the same name as the file in step 1, except changing the 'case' of one character.  For example, "Test".
5. Attempt to open new file.  Assuming the original file is still open, this will not appear to open the new file
6. Right click on new file and choose "Pull from mainframe".  This will update your screen (which is technically still editing the original file) with the data in the new file.  That is, no text, since no data was ever added to the new file.

**Expected behavior**

The two similarly but not identically named files should be treated as two different files, instead of, in some cases, "the same file".

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 1.18.1
- (Optional) Zowe CLI Version: 6.23.0
- (Optional) Are you using Secure Credential Store? No

**Additional context**

This is almost certainly caused by the fact that the Windows file system is case insensitive, while USS is case sensitive.  On Windows, the temporary file name, whether "test" or "Test" are in fact the same file.

**Comment by KutluOzel-b** [comment]
It is caused by the different case sensitivity in various operating systems. Even for ex : an instance of two macOS might have different settings for case sensitivity.  

**By my research and inspections :** 

- We can't change or set case sensitivity for a single folder ( our temp files folder ) from our app
- User can change this settings in MacOS and Windows ( Linux distributions isn't tested )

**Possible solutions :** 
- We can inform user to  change this settings in order to use capital sensitive named files and prevent creating / editing unless it is changed to case sensitive.
- We don't allow user to create same named files in the first place and just give a warning it is not supported
- We allow user to keep using this way and store each file with a hash and mapping method ( which will bring considerable amount of complexity to editing / creating temporary files and needs a testing on mainframe side as well for each modification on open files method )

By the discussion that we have in refinement this issue is on hold to wait other inputs and research.
