### ISSUE TITLE
No default zosmf profile found for ZOWE CLI

### ISSUE THREAD

**Issue by spufidoo** [zowe/vscode-extension-for-zowe#155]
Trying to install the zowe extension for vscode, I get the following after startup:

No default zosmf profile found for Zowe CLI. A default zosmf profile created with Zowe CLI is required to use the Zowe extension. Please [create at least one profile with Zowe CLI](https://zowe.github.io/docs-site/latest/user-guide/cli-configuringcli.html#creating-zowe-cli-profiles).

There is nothing but a zosmf_meta.yaml file in .zowe/profiles/zosmf
What should I put in it?

**Comment by zFernand0** [comment]
Hey @spufidoo,
You will need to create a profile with the Zowe CLI by following the documentation below:
https://zowe.github.io/docs-site/latest/user-guide/cli-configuringcli.html#creating-and-using-a-profile

**Comment by MikeBauerCA** [comment]
Documentation updated. It is also now possible to create profiles directly from the Zowe Explorer.

**Comment by jelaplan** [comment]
@MikeBauerCA & @jellypuno , it seems that if you start with no profiles in the .zowe > profiles > zosmf folder then the Zowe Explorer won't let you create a new connection. I closed VS Code and I went into that folder and moved out all the contents and then tried to restart then I get this error.  This might not be a common case but it doesn't get handled gracefully. 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/3207260/69650290-63670700-103c-11ea-88f3-031f851a07fa.png">

I tried again by shutting down, renaming the .zowe folder, and then restarted. This is probably a closer approximation to a totally new user who doesn't have the CLI. In this case, it works - that is I can create new connections. But, I do get the warning about no default profile that I wonder if is necessary because it is mostly creates worry in my mind that I'm already doing things wrong as soon as I begin. 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/3207260/69651804-a1fdc100-103e-11ea-81f0-e401ccbc7986.png">

**Comment by jellypuno** [comment]
@jelaplan so based on your error, this is what happened on the background. 

1. You deleted all your profiles manually including the zosmf_meta.yaml file which important. Hence your first 2 errors.
2. Then you renamed the .zowe folder and that allowed VSCode to create a new one with new profiles folder and created the zosmf_meta.yaml file. But unfortunately since you deleted your profiles you have errors 3 and 4 regarding your favorites.

One thing that I can tell you is that when I was new in Zowe I don't know about the .zowe folder. So if I needed to remove any profile, I use the CLI command for remove it. Deleting a profile would be a great feature in the Zowe Explorer. It can be added in the roadmap.

Regarding the error message, For me, I think it is helpful for total beginners meaning no favorites and no profiles at all. I would be informed of what I should do. But that is just my opinion.

**Comment by jelaplan** [comment]
Sorry if i can created some crazy. A conclusion I have is to eliminate the no default profile message. I think it is a holdover from the days when the Zowe Explorer extension had a dependency on the CLI for profiles. We no longer have that dependency so we don't need the message. 

I agree that new users won't know about .zowe folder and a delete profiles option in Zowe Explorer is a good idea but also a edit profile option. I know about .zowe and it is a handy way to edit the profiles relative to using the CLI but maybe I'm not as clever as I would like to be because I deleted the _meta file. Issue [319](https://github.com/zowe/vscode-extension-for-zowe/issues/319) exists for editing profiles in Zowe Explorer. This feature would make it less desirable to edit the .yaml files directly.

**Comment by jellypuno** [comment]
> Sorry if i can created some crazy. A conclusion I have is to eliminate the no default profile message. I think it is a holdover from the days when the Zowe Explorer extension had a dependency on the CLI for profiles. We no longer have that dependency so we don't need the message.

I am not sure. Maybe @jalel01 can help. Because I remember that we are discussing about this. The scenario is that I'm a new Zowe Explorer User and once I opened the extension then I have no idea what to do. The solution is the no default profile message.

**Comment by jelaplan** [comment]
It isn't uncommon for Web apps to start with a series of tooltips to guide the user. I think Broadcom even has a license for a tool to add this kind of thing. But, those are usually done with subtlety that this message lacks. If you open most apps, desktop or web, they don't prompt you. Consider MS word which doesn't tell you to create or open a document.

**Comment by jelaplan** [comment]
I created issue [332](https://github.com/zowe/vscode-extension-for-zowe/issues/332) for deleting a profile.

**Comment by jellypuno** [comment]
> But, those are usually done with subtlety that this message lacks.
I get it. If you feel strongly of removing it, I don't mind. 

> Consider MS word which doesn't tell you to create or open a document.
To be fair there are lots of training offered for MS Office. You can even have certification for this so I think it is an unfair comparison. I remember having a semester learning about it in grade school 😆 so now this is just a common knowledge for everyone.

**Comment by jelaplan** [comment]
I'd be more upbeat if the message appeared next to the action and directed the user. 
![image](https://user-images.githubusercontent.com/3207260/69659877-1fc8c900-104d-11ea-9000-83af47f182d7.png)
