### ISSUE TITLE
Correct Credentials Causing Invalid Credential Error Popup

### ISSUE THREAD

**Issue by matthewgrider** [zowe/vscode-extension-for-zowe#1571]
**Describe the bug**

A valid user attempts to use their sign-in on VSCode Zowe Explorer. 
After setting up a new zosmf profile and applying a filter they are given an "Invalid Credentials" popup. They then attempt to sign into the system using tso and can successfully sign in using the same credentials. 
They get the Invalid Credentials warning using their correct creds and then successfully sign into tso but there are no security violation listed in the sign-in report However if they were to purposely use incorrect credentials on Zowe Explorer and then correctly sign into TSO they do see sign-in violation messages. This leads us to believe the the actual credentials are correct but either the zowe permissions on the mainframe system or the vscode plugin are having issues with this particular user.

All other users work with the given setup. 

Is this a bug or incorrect setup?

**To Reproduce**

1. Setup zosmf Profile in Zowe Explorer
2. Apply filter and try to access datasets
3. receive 'Invalid Credential' error popup
4. Fail to open dataset

**Expected behavior**

Open, view and edit datasets with zosmf profile

**Screenshots**

![Annotation 2021-11-04 140255](https://user-images.githubusercontent.com/62899985/140412918-cf0b1144-7c57-4710-8ea0-e4c03a73104b.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 1.20.0
- (Optional) Zowe CLI Version: NA
- (Optional) Are you using Secure Credential Store? NO

**Comment by crawr** [comment]
Hi @matthewgrider , are you able to access z/osmf? There might be some more access permissions that you need.

**Comment by jellypuno** [comment]
@matthewgrider I am closing this issue because in my PoV, this is not a Zowe Explorer problem. The connection through Zowe Explorer and TSO uses different ports. There are several reasons why you are receiving the Invalid Credentials (Set-up, incomplete SAF resource definition, no access in z/OSMF but you have one in z/OS etc.) . I am not sure which one is applicable to you. I suggest you connect with your System Administrator.

Nevertheless, I wrote a [blog](https://medium.com/@jessielaine.punongbayan/quick-tip-of-the-day-update-your-mainframe-password-9319ab1d1817) about this. Hope this could help in debugging your issue.
