### ISSUE TITLE
Research how we could optimize our call for multi-select functionality

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1586]
As a ZE developer, I would to find a way on how we could optimize our code to implement the multi-select feature without duplicating code.

**Comment by JillieBeanSim** [comment]
@KutluOzel-b is research done?  I know we have implemented a lot of actions in multi-select. FYI @zFernand0

**Comment by KutluOzel-b** [comment]
They way we are doing it know to call inline processes within loops to have batch processes and some of the functionality, that requires a specific batch process, is implemented as a separate batch process.

I think to ensure avoiding duplications and single point maintenance for achieving same functionality for inline or batch processes is the way we are using it now. Otherwise if the other way is chosen , which is batch processes for every functionality for every multi select, would open new branches to maintain codebase which is not a good practice. 

Still some exceptions may be required in future depending on the functionality ( like all or none principle ) . For ex : delete all members of a pds if pds is completely deleted. ( I know our api does that but just for your imagination )

**Comment by JillieBeanSim** [comment]
closing as a duplicate to other multi-select issues
