### ISSUE TITLE
zowe.config.user.json not being leveraged properly

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#1620]
**Describe the bug**

Properties in `zowe.config.user.json` are not being merged with like-named profiles in `zowe.config.json`. In this situation, Zowe Explorer fails to start, and I receive the following error:
![image](https://user-images.githubusercontent.com/35504792/147107836-1f924963-a320-44b7-aadc-786df63af415.png)

**To Reproduce**

1. Add this content to your global `zowe.config.json`:
```
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "zosmf": {
            "profiles": {
                "lpar1": {"type": "zosmf","properties": {"host": "myhost.com"}}
            },
            "properties": {
                "port": 443
            }
        },
        "base": {
            "type": "base",
            "properties": {
                "rejectUnauthorized": false
            }
        }
    },
    "defaults": {
        "zosmf": "zosmf.lpar1",
        "base": "base"
        },
    "autoStore": false
}
```
2. Add this content to your global `zowe.config.user.json`:
```
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "zosmf-working": {
            "profiles": {
                "lpar1": {"type": "zosmf","properties": {"user": "myuser"}}
            },
            "properties": {
            }
        }
    },
    "defaults": {
        "zosmf": "zosmf.lpar1"
    },
    "autoStore": false
}
```
3. Launch VSCode and note that everything loads properly
4. In your global `zowe.config.user.json`, change `zosmf-working` to just `zosmf`
5. Relaunch VS Code and note this error on startup:
![image](https://user-images.githubusercontent.com/35504792/147108365-8d88fa4f-35e6-4154-ac4d-a39631f371cc.png)

**Expected behavior**

Zowe Explorer starts up and properties of like-named profiles in `zowe.config.user.json` override values in the `zowe.config.json`.

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: v2.0.0-next.202112161700

**Comment by crawr** [comment]
Upon further investigation, I found what seems like a bug in `loadSchema` in these lines:

<img src="https://user-images.githubusercontent.com/45845502/158576476-8196d20b-31b6-4aa3-8ece-67c6e1d4c29c.png" width="600" />
<img src="https://user-images.githubusercontent.com/45845502/158576295-1c3e7188-7b90-42ba-b112-b222b35e2208.png" width="600" />

Since the `profile.profLoc.osLoc` contains an array of 2 items, the `schemaMapKey` looks like:
![image](https://user-images.githubusercontent.com/45845502/158575545-1f793d40-2620-4488-ad7a-4991b503e48d.png)

and because `mProfileSchemaCache` looks like:
<img src="https://user-images.githubusercontent.com/45845502/158576053-69b7cef5-cd61-4f3c-b2b8-65f39c20b661.png" width="600" />

it is not able to find the correct schema and returns null. This causes the error message.

**Comment by zFernand0** [comment]
Should be fixed in https://github.com/zowe/imperative/pull/748

**Comment by JillieBeanSim** [comment]
@zFernand0 what version do we need of Zowe CLI to test that this issue is fixed?

**Comment by JillieBeanSim** [comment]
@zFernand0 so we should be able to test and confirm after this [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1693) correct

**Comment by zFernand0** [comment]
That's right.
One could also pull that branch and run the extension from the debugger in order to verify the functionality 😋
