### ISSUE TITLE
ZOWE V2 Explorer is logging "No default profile exists for type zosmf"

### ISSUE THREAD

**Issue by kraabrsg** [zowe/vscode-extension-for-zowe#1777]
**Describe the bug**

Vscode Extension Z open Editor / zowe explorer extension failed :

**To Reproduce**

1. install portable nodejs latest LTS Version
2. set "path" environment variable for nodejs, set "ZOWE_CLI_HOME" environment variable
3. npm install -g @zowe/cli 
4. npm install -g axios
5. zowe plugins install @zowe/cics-for-zowe-cli@zowe-v2-lts @zowe/db2-for-zowe-cli@zowe-v2-lts  @zowe/zos-ftp-for-zowe-cli@zowe-v2-lts
6. zowe config init --global-config --promt false
7. zowe config set --secure profiles.base.properties.user --global-config

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/86772851/166406938-001b944b-822f-48ae-8df7-c3fb1c010783.png)

**Desktop (please complete the following information):**

- OS: WIN 10
- Zowe Explorer Version: 2.0.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**
See original errors and logs:  https://github.com/IBM/zopeneditor-about/issues/238

We use it in combination with our own VSCODE Extension.

**Comment by phaumer** [comment]
@kraabrsg could you show us the output of this command to check that there is really only the config file involved that you attached to https://github.com/IBM/zopeneditor-about/issues/238 ?

```bash
zowe config list --locations --root
```

**Comment by kraabrsg** [comment]
Hi @phaumer, i allready deleted that, and did a "re-setup" but the output is correct:

```
C:\Users\MYUSER>zowe config list --locations --root
C:\Entwicklung\tools\zowe\zowe.config.json
```

**Comment by phaumer** [comment]
@kraabrsg, @zFernand0 is working on a fix for using the CLI env variables in Zowe Explorer to set the location here: https://github.com/zowe/vscode-extension-for-zowe/commit/895d534cf30522cd7096961107a784e490819604  

As a workaround can you move your config file and schema into your ~/.zowe folder for now?

**Comment by zFernand0** [comment]
Hey @kraabrsg,

Here is a VSIX for the Zowe Explorer extension: [vscode-extension-for-zowe-2.0.2-SNAPSHOT.vsix.zip](https://github.com/zowe/vscode-extension-for-zowe/files/8677499/vscode-extension-for-zowe-2.0.2-SNAPSHOT.vsix.zip)

Since the error messages are coming from the `zopeneditor.` (zOE), I can't say for sure that just the VSIX above will solve the problem.

Hence why I'm also living the `.tgz` package in case it needs bundled with the zOE VSIX.
[zowe-zowe-explorer-api-2.0.2-SNAPSHOT.tgz.zip](https://github.com/zowe/vscode-extension-for-zowe/files/8678064/zowe-zowe-explorer-api-2.0.2-SNAPSHOT.tgz.zip)

FYI, @phaumer

**Comment by phaumer** [comment]
Thanks @zFernand0 this could be tested just with Zowe Explorer to check if the right profiles are now loaded into the trees and are working @kraabrsg.

**Comment by kraabrsg** [comment]
Tried installing the new zowe explorer Version, this alone does not solve the error. 
FYI: @phaumer  @zFernand0

**Comment by zFernand0** [comment]
Hey @kraabrsg,
Thanks for trying it out. 

Did Zowe Explorer load the profiles from your `ZOWE_CLI_HOME` location?
>C:\Entwicklung\tools\zowe\zowe.config.json
Not sure if zOE needs to be disable so that it doesn't override any functionality provided by ZE.

If so, that's one step in the right direction. 😄  We will just need to bundle the same fixes in zOE 😋

**Comment by kraabrsg** [comment]
> 

Yes this new Version loads the profiles (zowe explorer seems to work like expected). It does not matter if z open editor is disabled or not (zowe explorer does not care). Thanks! :-)

**Comment by zFernand0** [comment]
Thank you very much for confirming that ZE behaves as expected (and for the quick response too) 😋

**Comment by phaumer** [comment]
Thanks for testing this @kraabrsg. For Z Open Editor we need to wait for the fix to be published and then we need to republish the editor.
