### ISSUE TITLE
Update profile does not work when non-secure credentials are missing in the first place

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#1804]
**Describe the bug**

When you disable secure credentials in a config file and then run the Update Credentials command it allows you to enter data and shows you a success message, but does not update the json file.

**To Reproduce**

- Create config file without secure fields and not autoload, no username and password properties
- Test that it works prompting you for credentials
- Right-click Update Credentials
- Enter credentials
- Success message
- Check the config file

It works when credentials are available in config file.

**Expected behavior**

Either an error message explaining that the properties are not available or the command adding the entered credentials to the profile. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Any
- Zowe Explorer Version: 2.0.1
- (Optional) Zowe CLI Version: 7.1.1
- (Optional) Are you using Secure Credential Store? no

**Additional context**

**Comment by zFernand0** [comment]
In order to achieve plain text credentials, you should emove all fields from `secure: [ ]`, and set the `~/.zowe/settings/imperative.json` file to:
```json
{
  "overrides": {
    "CredentialManager": false
  }
}
```

In my case, I'm seeing this error message (which is wrong too)
![image](https://user-images.githubusercontent.com/37381190/172171951-ed302910-dad7-49f5-abad-1338089f2980.png)

I would expect the Update Credentials to update the profile, (securely or not) 😋
