### ISSUE TITLE
Master build broken - NLS Support

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#195]
npm run package failing 
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/30794003/63002641-4c761d80-be6e-11e9-84ac-064eb6cde84f.png">

**Comment by Colin-Stone** [comment]
Gulp package needs to precede node stringUpdateScript.js

What is the effect of adding these extra steps does it leave more files that need cleaning up before the files get packaged?.

**Comment by Colin-Stone** [comment]
I get the same issue with additional information
`[15:44:55] Starting 'internalNlsCompileTask'...
src/DatasetTree.js(281,78): second argument of a localize call must be a string literal.
[15:44:59] 'internalNlsCompileTask' errored after 3.67 s
[15:44:59] Error: Failed to rewrite file: /Users/stonecc/git/vscode-swap/out/src/DatasetTree.js`

**Comment by Colin-Stone** [comment]
So it looks as if the critical piece is this `After adding/updating/removing any string, run npm run package. This will update the sample directory under the i18n folder with the newly added strings. Upload these files to Zanata or email a maintainer to do so.`
And that these files also need to be uploaded to git not just provided to zanat etc

**Comment by lauren-li** [comment]
PR #197 will hopefully address this.

@Colin-Stone This is more a rearrangement of steps rather than an extra step. The gulp command was moved into the npm build script, which runs before `npm run update` in the vscode:prepublish script. (`npm run update` will run stringUpdateScript.js, which expects files produced by the gulp command.)

Also, since we were having issues with the gulp task removing but not replacing the testProfileData .js and .map files in the out folder, I added `"resources/testProfileData.ts"` into the tsconfig includes. If there are any adverse side effects of this that you can think of, please let me know. Thanks!

**Comment by Colin-Stone** [comment]
Thanks for fixing @lauren-li

**Comment by lauren-li** [comment]
@Colin-Stone Thank you for your help looking into this! I'd also like to thank my teammate Prasang for his guidance on the npm issue.
