### ISSUE TITLE
refreshAll error showing with trees

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1994]
**Describe the bug**

![Screen Shot 2022-10-31 at 3 48 17 PM](https://user-images.githubusercontent.com/49491949/199097485-f1620a5e-4226-4f4b-b533-7980f583cc61.png)

`zowe.jobs.refreshAllJobs' not found` has also been presented to users

user also reported this

![Screen Shot 2022-11-02 at 7 59 36 AM](https://user-images.githubusercontent.com/49491949/199484563-317aefca-bac8-49b8-83f3-832a01df0fe1.png)

**Comment by t1m0thyj** [comment]
The cause of this issue seems to be when an empty workspace with no folders is open in VS Code, then Zowe Explorer fails to activate.

Until we release a patch to fix the issue, some workarounds are:
* Add a folder to the workspace (`File` -> `Open Folder`) and reload the VS Code window.
* Close the workspace (`File` -> `Close Workspace`) and reload VS Code without a workspace or with a non-empty one.
