### ISSUE TITLE
'Remote file has been modified' loop when working with PDS/PDSE

### ISSUE THREAD

**Issue by BernardoFern** [zowe/vscode-extension-for-zowe#2007]
Bug description:
When using the Zowe Extension for VSCode and performing an edit and save to a dataset member of a PDS or PDSE, an error message is issued by VSC.

Steps to reproduce:
1. Create a new partitioned dataset;
2. Create a new member within this new dataset;
3. Edit-in data, save the member;
4. Edit-in data again, save the member again;

Observed issue:
Source is refreshed: the vscode tab to edit member goes blank momentarily, and the data reappears;
The following error message is issued by vscode, when the local and remote sources actually match:
![image](https://user-images.githubusercontent.com/117918335/201106522-e8705189-c351-4a88-ad3c-69f08c77e4f8.png)
.
Pressing 'Overwrite' or 'Compare>Overwrite' leads to the file being saved and therefore issuing the error message from the previous image again.

System configuration:

- OS: Windows 10 build 19044.2130
- Zowe Explorer Version: v2.4.0
- Zowe CLI Version:  7.6.1
- Are you using Secure Credential Store? Yes

Additional comments:
Not a deal breaker, but this bug renders vscode autosave feature completely unusable. A user that might have it on will be unable to perform any changes as the file is saved on the server side constantly.

**Comment by traeok** [comment]
@BernardoFern can you confirm the dataset type that you are testing with? We tried doing this with a PDS, but are are not facing that problem. With a LIBRARY type, there seems to be an underlying API issue as the Etag is not accepted.

**Comment by traeok** [comment]
I stand corrected - we were able to reproduce the problem with PDS within Zowe Explorer, but when using the API directly, the PDS type seems to work. With LIBRARY/PDSE types the API seems to have problems with the API. Going to spend some time today doing some further API testing and will update.

**Comment by BernardoFern** [comment]
My apologies, I was sick shortly after I submitted the bug. Thank you for investigating this.
This issue was observed for a PDS (not a library). Cheers

**Comment by traeok** [comment]
No worries! Thank you for the clarification. We did some further testing and the issue seems to be related to mainframe profiles/permissions on the LPARs. @t1m0thyj was not able to replicate this issue as the API is working as intended and returning the proper return codes, but I was able to reproduce this problem with my account. We are going to follow up with the z/OSMF team on this issue, as well as some further testing and will report back with updates. Thanks for your patience!

**Comment by traeok** [comment]
@BernardoFern Sorry again for the delay, we did hear back from z/OSMF and the issue seems to arise from 8-character username IDs. A fix is currently in the works and I will follow-up when we get an update from the z/OSMF team 🙂

**Comment by traeok** [comment]
Hi @BernardoFern ,

We've received news that the fix is publicly available in the following PTF: https://www.ibm.com/support/pages/apar/PH52243?mhsrc=ibmsearch_a&mhq=UI90625

I've done some testing locally to confirm that this PTF has resolved the issue 🙂 so, I will mark this as resolved. Feel free to reply to this thread if the issue still appears for you after having installed this PTF.

Thanks!
