### ISSUE TITLE
Provide Release tags

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#207]
As the VS Code extension is under heavy development there are breaking changes from time to time requiring that one can go back and manually build an older version that was still working. 

In the VS Code marketplace the Changelog does not tell me when a version was release and the repo also does not tell me. The version number updates in the package.json also do not seem to be a good indicator. 

To make the extension consumable and releasable it is essential to baseline the code for each marketplace release so that one can go back and branch of any earlier release in case of breakages. There are other advantages to baselining as well.

Github provides Release Tags for that: https://github.com/zowe/vscode-extension-for-zowe/releases. See here how to use them: https://help.github.com/en/articles/creating-releases.

**Comment by Colin-Stone** [comment]
It is worth remembering that we have not reached GA and the code is still under development. Consequently all should be marked pre-release? (Question/Statement)

**Comment by zFernand0** [comment]
As long as we remain at the `0.x` level, we should be prefectly fine with making as many breaking changes as we need to.

As for release tags, I remember this is something that was proposed before but was shutdown because of the fear of inconsistency since the versioning on the VSCode Extension is being done "by-hand".

Would it be worth automating such process? Or at least using a combination of commands to do the versioning (i.e. `npm version <version-number> && git push --tags`)?

**Comment by phaumer** [comment]
@zFernand0 0.25 was published to the marketplace without creating a tag again. Is it not possible to create a release tag manually for now? It is something you can do with two mouse-clicks in github. If you ping me in Slack I could do it next time we publish perhaps.

**Comment by zFernand0** [comment]
Thank you so much for the reminder.
I was working on adding it to the pipeline.
I will open a PR for it in the next hour.
In the meantime, I've manually created one for this release.
I'll add a tag for the previous release corresponding to the [CHANGELOG](https://github.com/zowe/vscode-extension-for-zowe/blob/master/CHANGELOG.md)

**Comment by phaumer** [comment]
Thanks so much. Very much appreciated @zFernand0 !
