### ISSUE TITLE
Improve speed of loading quick pick for Add Profiles

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/vscode-extension-for-zowe#212]
After clicking "Add Profile", there is often a significant delay before the quick pick appears. Currently a separate instance of Node is spawned to obtain the list of profiles, in order to support the Secure Credentials plugin which contains native code.

The extension could check the Zowe config to see if a credential manager is enabled. If not, the profile list could be obtained without creating a Node instance which would be faster.

**Comment by MikeBauerCA** [comment]
I have seen this cause issues in practice. Users do not wait for things to happen as they expect an immediate response. This causes folks to click the "Add Profile" button multiple times which spawns multiple operations. 

If we cannot improve the performance for folks using the Secure Credential Store plugin, then we should prevent the issue of folks clicking the button multiple times and spawning multiple operations.

@tucker01, I believe we found a separate issue with accessing the secure credentials from VS Code related to the credentials being created with a different version of the CLI than the one in the package used by the Zowe VS Code Extension. As part of #226, users, who store connection details in VS Code settings, will be prompted for username and password when using a specific connection in a session. Perhaps we should take a similar approach for users of the secure credential store plugin. What are your thoughts on this?

**Comment by tucker01** [comment]
@MikeBauerCA, Are you still looking to support both CLI profiles and `settings.json`? If that is the case, and the user has the profile, seems confusing that they would have to retype their credentials? 

I'd rather see the "click to add profile" removed in favor of having a CLI profile list in `settings.json`. Set and forget... my required profiles are available every time I launch vscode.

**Comment by MikeBauerCA** [comment]
@tucker01, yes I would like to support both CLI profiles and `settings.json`. I agree that ideally users of the secure-credential-store would not need to retype their credentials. Perhaps there is a technical resolution to the issue with accessing the secure credentials from the Zowe VS Code Extension when a different version of the CLI package was used to create the profiles.
 
Persistence of added profiles (set and forget) will be provided upon resolution of #210. I think having a button to add profiles to the view is more intuitive and provides a better UX than requiring users to set it in `settings.json`. That said, I am in favor of ultimately storing this information in `settings.json` so users can fully configure the extension via `settings.json`.

**Comment by tucker01** [comment]
I don't follow... The "technical resolution" is spawning a node process using the same version of node.js that created the credentials. If something isn't working with loading secure credentials, we need to open an issue. 

This issue is about UI response time. I believe there is an API you can use to get profile names without involving the secure credential store. If we switch to using that, "click to add" should be near instant. You'll still have a small delay when loading the contents, but perhaps that can be done async in the background when the profile is added to the tree.

**Comment by Colin-Stone** [comment]
I've restructured the profiles code to support #210 and made it more economical in loading profiles. In other words it does it once rather than multiple times during initialization. 

I built in a profiles refresh option and since each of the views have a refreshAll button I have  hooked it in to refresh not just the contents but to reload the profiles all over again. I'm considering putting this behind a progress indicator to slow any speedy fingered types that want to stack up key presses.

I think I read somewhere that it may be possible to bypass the node process spawning if we could ascertain that it's not required. I would quite like to build that in too. Can anyone provide the magic formulae I need for that?.

**Comment by tucker01** [comment]
I don't think we'll be able to (at this time) avoid launching the process, but we should at least be able to get the profile names must quicker I think.

The `BasicProfileManager` in `imperative` should have a method called `getAllProfileNames()`. That will give you all profile names for a given `type` (e.g. zosmf). We should be able to use this to get the names very fast for the quick-pick. Once the profile is selected however, it'll take a moment to load.

**Comment by tucker01** [comment]
The rub is keytar and secure credential management and how node bindings/native code work. We can load the profiles almost instantly, but if they're securely stored... its a different matter. I'd be nice if vscode supported some kind of secure management of properties, but I believe its been requested and not planned.

**Comment by Colin-Stone** [comment]
So what I currently have in the branch is to load all of the zosmf profiles anyway at initialization time and cache them. This means a list of names is available for the quickpick, unless the user adds something new. For this scenario the user would need a refresh. 

I think there may be value in using the cli call to get the names each time however. This is because it will identify  if the user is accessing a new name not in the profile cache in which situation the refresh would be invoked automatically.

**Comment by tucker01** [comment]
Nice. Caching is a good way to go, I'm guessing then you can launch the process once and gather all profiles... that would definitely speed things up. If it can be refreshed automatically... even better.

**Comment by tjohnsonBCM** [comment]
> I think I read somewhere that it may be possible to bypass the node process spawning if we could ascertain that it's not required. I would quite like to build that in too. Can anyone provide the magic formulae I need for that?.

In `~/.zowe/settings/imperative.json`, there is a JSON setting `overrides.CredentialManager`. By default it is set like this:
`"overrides": { "CredentialManager": false }`

When the Secure Credentials plugin is installed, it changes to this:
`"overrides": { "CredentialManager": "@brightside/secure-credential-store" }`

I'm not sure how convenient it is to access this settings file from the VS Code extension, but this would provide the logic needed to determine whether a separate node process should be started, based on whether `CredentialManager` is set.

**Comment by tucker01** [comment]
Another approach would be to spawn the node process as service worker that lives in the background with imperative initialized on startup. Other extensions take a similar approach for various reasons. 

This would eliminate the need for caching, allow you to take advantage of the direct imperative APIs for loading, and definitely improve response time.
