### ISSUE TITLE
Refreshing the USS view causes alternating leading space before filter

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/vscode-extension-for-zowe#2155]
**Describe the bug**

After filtering USS files, refreshing the tree causes an alternating space to be added before the filter in the tree item's label.

**To Reproduce**

1. Apply a filter to the USS view
2. Refresh the view multiple times

**Screenshots**

![RefreshUSSWithFavorites](https://user-images.githubusercontent.com/122040687/221001618-edfa2619-4da4-47d6-b54e-9ce0ac78a42e.gif)

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: 2.6.1

**Comment by traeok** [comment]
The issue is coming from our `labelRefresh` helper function:

![image](https://user-images.githubusercontent.com/86500639/221684537-395c06b1-3af6-48b1-bb85-0ef834603469.png)

It is adding a space to the end of the session name, shifting the description/filter to the right as a result.
We might have to change the way we are refreshing labels in order to resolve this issue.
