### ISSUE TITLE
Replace Webpack 4 with newer bundler

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#2214]
Microsoft has upgraded away from Webpack 4 in their VSCE samples so we are falling a bit behind now 🙂 https://github.com/microsoft/vscode-extension-samples/blob/main/webpack-sample/package.json

For the v3 release, we could investigate alternatives like Webpack 6 or Turbopack (used in the K8s repo).

**Comment by traeok** [comment]
Did some research into popular bundlers. Here are a list of modern bundlers that we can also choose from:

https://github.com/zowe/vscode-extension-for-cics/issues/322#issuecomment-1468380743

**Comment by traeok** [comment]
here is another bundler option: https://www.rspack.dev

**Comment by rudyflores** [comment]
Additional information on RSPack vs Turbopack: https://www.rspack.dev/guide/introduction.html#compared-with-turbopack

**Comment by rudyflores** [comment]
## NPM vs Yarn vs PNPM

### Tradeoffs

Feature | pnpm | Yarn | npm
-- | -- | -- | --
Workspace support | ✔️ | ✔️ | ✔️
Isolated node_modules | ✔️ - The default | ✔️ | ✔️
Hoisted node_modules | ✔️ | ✔️ | ✔️ - The default
Autoinstalling peers | ✔️ | ❌ | ✔️
Plug'n'Play | ✔️ | ✔️ - The default | ❌
Zero-Installs | ❌ | ✔️ | ❌
Patching dependencies | ✔️ | ✔️ | ❌
Managing Node.js versions | ✔️ | ❌ | ❌
Has a lockfile | ✔️ - pnpm-lock.yaml | ✔️ - yarn.lock | ✔️ - package-lock.json
Overrides support | ✔️ | ✔️ - Via resolutions | ✔️
Content-addressable storage | ✔️ | ❌ | ❌
Dynamic package execution | ✔️ - Via pnpm dlx | ✔️ - Via yarn dlx | ✔️ - Via npx
Side-effects cache | ✔️ | ❌ | ❌
Listing licenses | ✔️ - Via pnpm licenses list | ✔️ - Via a plugin | ❌

### Node.js support for PNPM

Node.js | pnpm 5 | pnpm 6 | pnpm 7 | pnpm 8
-- | -- | -- | -- | --
Node.js 12 | ✔️ | ✔️ | ❌ | ❌
Node.js 14 | ✔️ | ✔️ | ✔️ | ❌
Node.js 16 | ?️ | ✔️ | ✔️ | ✔️
Node.js 18 | ?️ | ✔️ | ✔️ | ✔️
Node.js 20 | ?️ | ? | ✔️ | ✔️

### Performance and Disk Efficiency

- **NPM**: It is bit slower when compared to Yarn and PNPM.

- **YARN**: Yarn uses the same flatten node_modules directory but is comparable to NPM in regards to speed and installs packages parallely.

- **PNPM**: PNPM is 3 times faster and more efficient than NPM.  With both cold and hot cache, PNPM is faster than Yarn.

<img src="https://github.com/zowe/vscode-extension-for-zowe/assets/68666202/521b7c25-8c52-4aae-95e2-3acf4dfc8164" width="512" height="512" />

### Security

- **NPM**: There have been some security vulnerabilities that have directly affected many projects due to the way npm handles bad packages.

- **YARN**: Checksums stored in yarn.lock have been used by Yarn Classic and Yarn Berry ever since. Yarn also prevents you from installing malicious packages; if a mismatch is detected, the installation will be aborted.

- **PNPM**: Similar to Yarn, PNPM also uses checksums and in addition to the use of checksums, pnpm also verifies the integrity of its code before executing it.

### Sources

- https://pnpm.io/installation#compatibility
- https://pnpm.io/feature-comparison
- https://www.atatus.com/blog/npm-vs-yarn-vs-pnpm/#:~:text=NPM%3A%20It%20is%20bit%20slower,PNPM%20is%20faster%20than%20Yarn.
- https://dev.to/ayoub3bidi/lets-settle-things-out-2-npm-vs-yarn-vs-pnpm-5e04

**Comment by JillieBeanSim** [comment]
closing with PR #2685 merged
