### ISSUE TITLE
Add properties view for files on USS

### ISSUE THREAD

**Issue by rudyflores** [zowe/vscode-extension-for-zowe#2254]
In Zowe Explorer it would be nice to have a right click menu option on a file for viewing it's properties. These properties could be things that usually become list in file on USS like:

- Tag of the file (utf-8, ISO-*, etc)
- Timestamp of last edited
- Read/write permissions

This could be displayed when clicking on a menu option with the label `properties` in it and displaying a read-only file with those properties being listed.

**Comment by traeok** [comment]
Something we could consider implementing for this: an interactive webview where users can modify the tag, user permissions, ownership, etc.

Since VS Code has React elements available for the web view, we could display the React components and add logic to those components to call ZE APIs for certain UI actions.
