### ISSUE TITLE
Allow data sets and data set members to be copied

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#233]
Depends on zowe/zowe-cli#521

**Comment by CForrest97** [comment]
Following the wireframes in #262 I have 2 separate actions: `copy` and `paste`. Should these commands interact with the users clipboard in a similar way to how copying files works in base VSCode. Or should the copying command just save the details in either memory or a context variable?

**Comment by Colin-Stone** [comment]
> Following the wireframes in #262 I have 2 separate actions: `copy` and `paste`. Should these commands interact with the users clipboard in a similar way to how copying files works in base VSCode. Or should the copying command just save the details in either memory or a context variable?

I haven't used the clipboard. What I would want to check  is what would happen if the objects were pasted elsewhere. I suggest you experiment with that approach to see if anything useful such as if formatted text appeared, if so go with that otherwise its keep in memory.

**Comment by CForrest97** [comment]
It seems that VSCode adds access to writing and reading text to the clipboard. So the only way to utilise the clipboard would be to encode the data set name, profile name and optionally the member name in a string (either in JSON.stringified or in the same format as the favourites - [profile]: dataSet[mem])
This would mean if the data was pasted elsewhere it would output the encoded string.
The benefits I see to having the data stored in the clipboard:
- If the user closes and reopens VSCode the copied data set remains
- The user can copy from one VSCode window and paste into another
- The behaviour is similar to how VSCode handles file copying

The drawbacks for using the clipboard instead of storing the data in a variable in memory:
- It will overwrite anything the user has already copied into their clipboard
- If the user copies anything else inbetween copying a data set and pasting the data set, the data set information will be overridden.
- If the user pastes the data into a text editor they will see the data we are storing in the clipboard when it could be hidden from them

**Comment by CForrest97** [comment]
resolved in #326
