### ISSUE TITLE
Zowe is the Variant

### ISSUE THREAD

**Issue by lnginyard** [zowe/vscode-extension-for-zowe#2401]
Type: <b>Bug</b>

Extension bisect continues to report Zowe Explorer when performing extenson bisect. I've been having issues with Zowe in not only VS Code but the Insiders edition as well, which I've opened up an issue on previosuly and havent been able to find a resource to close the issue. I am not sure if it's only me or if anyone else is experiencing issues but to reporduce the problem I suggest performing a extension bisect on all of your extensions to see that Zowe is the last extension that being reported and causing the developer to not be able to reproduce. 

Extension version: 2.9.1
VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|148, 359, 342|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id fdd60ec0-9d5a-47d0-90b8-aed724734cd4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
gsofa:30797621
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589
cmakesidepanelv2:30779593

```

</details>

**Comment by JillieBeanSim** [comment]
Hey @lnginyard I am sorry you are having issues with Zowe Explorer and VS Code.  I did leave a question in the mentioned issue a couple of weeks ago and still waiting a response https://github.com/zowe/vscode-extension-for-zowe/issues/2369#issuecomment-1628772759.
I also went through the steps listed above with VSC's Extension Bisect and when Zowe Explorer is installed and the last extension in the alphabetical list it will show as the extension causing the issue when `I can't reproduce` is selected the entire time.  I disabled Zowe Explorer and went through the same process and the Extension Bisect shared that the last extension (active) was the culprit since I selected `I can't reproduce` throughout the process, this time it was SonarLint.  With extension bisect we need to try to reproduce the issue seen before sharing whether we can reproduce or not.  Are there some steps we can take to try to reproduce the issue seen with each extension during the checks?  A list of installed extensions would help us recreate the environment as well.

**Comment by lnginyard** [comment]
So, I don't think that I used the extension bisect correctly. Since you explained how to use it I see why Zowe the explorer was showing as the extension causing the issue. I have over 100 extensions installed in VS code so to give you a list would be exhausting but what I can do is try to narrow down the issue by deleting all of my extensions and then downloading Zowe to see if it operates correctly and doesn't cause any issues.

I believe the issue that you commented on last week was that the Zowe extension was not showing up on the side extension list but recently I've been able to locate it so I will be closing that issue shortly after I check to make sure that it is still visible on the side. 

Thank you for all of your help thus far @JillieBeanSim  !
