### ISSUE TITLE
zowe explorer enhancements request

### ISSUE THREAD

**Issue by kzafiropoulos** [zowe/vscode-extension-for-zowe#2592]
Dear Madam/Sir
I am creating the case here  as there is no code4z or zowe category for new ideas on https://community.broadcom.com/ideation/allideas.

New requests:
 
1) Option for Sort members by creation date (Sort by Created)

2) Search for a string in all library members (similar to SRCHFOR of ISPF)
 
3) Find members in filtered datasets (similar to mem command of ISPF)
Kind regards
Konstantinos Zafiropoulos

**Comment by zFernand0** [comment]
Hey @kzafiropoulos 

1. Great feature request 😋 
    - I believe some work was completed around sorting of members in Zowe Explorer, so make sure to update to the latest version and let us know.
  
2. I believe a similar enhancement request was opened regarding the ISPF search functionality but we closed it due to inactivity.
    - https://github.com/zowe/vscode-extension-for-zowe/issues/449
    - Please feel free to leave a comment on the issue below and we will consider it if/when it gets enough upvotes (👍🏽)

3. VScode provides an automatic search capability that gets triggered when you start typing the name of the node (in this case the member name). Here is a GIF that might help illustrate these capabilities.
    - Note: I make sure the focus is on the dataset, and typed the characters `IEF`
      ![IEF search](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/7ef5c494-967e-4fc2-b002-9c3ecce0955c)


---

For future reference:
- Please fill out the template as much as possible 😋 
- If you are a user of the Broadcom Code4z pack, feel free to create an issue in the BroadcomMFD/Code4z repository:
https://github.com/BroadcomMFD/code4z/issues/new

**Comment by traeok** [comment]
Hi Konstantinos,

To help organize our issues and track them individually, I will part these out into individual issues and redirect you to existing issues if available:

1. An issue has been created for this enhancement; please refer to issue #2565.
2. I have reopened issue #449 because this seems related; if you have any additional details as part of this request, feel free to add them to that issue.
3. I have created a new issue (#2630) to track this request; feel free to add to this issue if you would like to provide more info for this request.

Thank you for submitting these enhancement requests!
