### ISSUE TITLE
Favorites icon: Change the icon for Favorites to show a star icon.

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#310]
It is common to use a star icon for favorites. This would be more immediately recognizable. 

<img width="271" alt="image" src="https://user-images.githubusercontent.com/3207260/69113109-0a054380-0a50-11ea-96ab-b8480d5b417f.png">

**Comment by Colin-Stone** [comment]
Do we have access to someone with UX skills who can create svg icons please (16x16) I have tried but not my forte.

**Comment by jelaplan** [comment]
> Do we have access to someone with UX skills who can create svg icons please (16x16) I have tried but not my forte.

I will ask Patrik Bubak who is a UX designer to create a SVG star icon.

**Comment by Colin-Stone** [comment]
That's great thanks John and maybe we would want to develop our own family of icons in the future

**Comment by jelaplan** [comment]
> That's great thanks John and maybe we would want to develop our own family of icons in the future

That would be possible. If you need icons created then me and Patrik can most likely create them.

**Comment by bubpa01** [comment]
Is it possible to acquire the original SVG for the icon that I could change?

**Comment by Colin-Stone** [comment]
Hi Patrik. If you look in resources/dark and resources/light there are all of the icons. I originally took these from VSCode minimal set which seemed to work well and then tweaked them.

**Comment by bubpa01** [comment]
![image](https://user-images.githubusercontent.com/58072638/69425590-825b5580-0d2b-11ea-84a3-a40479eb69c3.png)

**Comment by bubpa01** [comment]
Thanks for the responses guys.

I'm hosting the icons in Figma - our official web-based collaborative design tool. You should be able to see them via [this link](https://www.figma.com/file/MvlsCEJMGIW3zBqWDI7xFN/VS-Code-Icons?node-id=0%3A1).

**Comment by jelaplan** [comment]
Thanks Patrik

**Comment by jelaplan** [comment]
@Colin-Stone are there other icons that you are concerned about?

**Comment by Colin-Stone** [comment]
Thaks for the offer. This will be ongoing work so no rush but I would like to have some more document icons at some stage that possibly using decorators subtley represent some z/OS specific concepts.

- Binary file
- Archived or Migrated dataset file or folder
- A dataset alias
- A job
- A job spool
- Possibly Type specific ? asm, cbl, pli, copybook etc

And at the risk of sounding ungrateful can I have both light and dark versions please ;-)

**Comment by Colin-Stone** [comment]
Wow there are several concepts on show here. Thanks guys for looking at this and proposing some great ideas.

My favorite so far is this but I notice you don't really talk about it so am I right that we can't do it?. 
![image](https://user-images.githubusercontent.com/30794003/72876317-22af0580-3cee-11ea-9110-b8951593bf50.png)
Indeed one of my frustrations has been that I want to be able to create a VSCode TreeItem label that combines different elements for example, here I want to combine details of the root location with a profile identifier. Ideally these would be two distinct elements, preferably different color and/or font. Hence why your image above struck a chord with me. However I cannot see how it could be achieved in VSCode.
![image](https://user-images.githubusercontent.com/30794003/72876470-79b4da80-3cee-11ea-8f13-a30b6c554903.png)

It sounds however that we could have an indicator over on the right and this is a definite step forward albeit with the caveat that we may be encroaching into an area reserved for action items. Does this mean at the expense of being able to add Action items as I don't think that ideal particularly with options for the Zowe Explorer to be extended or are we just saying a bit cluttered?. 
Letters in the icon is still a possibility.

I agree a 16x16 icon does not lend itself to adding characters however I have seen several VSCode themes that simply use the suffix or a specific visualisation of that. For example
![image](https://user-images.githubusercontent.com/30794003/72877473-e4ffac00-3cf0-11ea-9999-9340b1d5f24c.png)
..which is why I like the top one for JCL in a box (albeit not 16x16 of course)

### The wider effect (dilema)
Some of the examples for VSCode icons generally available have reasonable graphical metaphors for the types of files they represent but maybe too much for what we need and potentially make things look untidy. Up to now I have generally been thinking of Datasets with JCL, Cobol or Assembler but should we be considering the Zowe Explorer USS and Jobs sections too?. The USS section could use some of the VSCode specific icons for C, Java etc but should we go that route or try and keep all three sections with the same look and feel?. 
- Jobs as covered earlier is simpler and would have just two graphics. The ubiquitous cog to represent a process/job and log graphic for the spool files maybe?. 
- USS is maybe not such a big issue since the suffix is included in the filename anyway.

### So how about...?
- If it is possible could we go with the label enhancement or additional label on the right hand side. Generally this would only apply to a PDS (or folder). There isn't any additional value of indicating every member as being JCL if the folder already highlights this. Yes there may be individual PS files which we may want to highlight too but by mainly adapting the folder tree elements we don't usually have action items associated. Getting even more clever and for the future. How about if the labal is an actual action item which would allow a user to specify the association from a preselectable list?.

**Comment by bubpa01** [comment]
Allow me to post some examples here and explain why what could work and why not,

![image](https://user-images.githubusercontent.com/58072638/72890286-decdf780-3d11-11ea-8d3f-6bdbb01e3694.png)
The above image isn't ideal for a number of reasons, mainly:

- information fluidity with items that are not organised is disrupted
- hinders the possibility to sort items based on their suffix (if such a feature would be desired in the future)

![image](https://user-images.githubusercontent.com/58072638/72890437-2bb1ce00-3d12-11ea-890b-95ce87347659.png)
The example above demonstrates consistency through a clearer structure and allows the user to find all pieces of information in one place, respectively.

This should eliminate concerns in the future about character limit in filenames. All actionable items along with the file type are easy to access to the right.

**Comment by bubpa01** [comment]
**About the icons**
I would strongly advise against complexity, especially in the case of our icons that are very small (averaging on 16 pixels). The above works well on 100%, but with some compromises:

- had to refrain from adding additional icons into the green dot. The icon now (hopefully) conveys an item has been pulled. Instead, I went with lowering opacity and include only a small green dot to say: 1) item has been pulled, 2) operation was successful
- choosing to place the filename text into an icon or making it smaller or both would render it illegible

**Comment by jelaplan** [comment]
Here is how VS Code handles status bar. It is an animated line that moves back and forth across the header. That is a possible way to show the file is downloading from the MF. That is instead of a file icon that blinks or something like that. I'm concerned with trying to do too much with an file icon by showing it both pulled, unpulled, and animated while downloading. If VS Code already has a standard way to show status or background activity is happening, then I'm inclined to go with that. 
![image](https://user-images.githubusercontent.com/3207260/73077407-1d88bc80-3e8e-11ea-8aca-2362b9d50158.png)

**Comment by Colin-Stone** [comment]
> If VS Code already has a standard way to show status or background activity is happening, then I'm inclined to go with that.

I've just implemented https://github.com/zowe/vscode-extension-for-zowe/pull/465 which wraps the call in a progress status in the bottom right

**Comment by katelynienaber** [comment]
@bubpa01 Would it be possible to get the Favorite (star folder) icon in light version?

The others we just converted to black but for this one the yellow star is hard to see on a light layout.

And I don't know what would look good ^^''
