### ISSUE TITLE
Support deleting a profile

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#332]
The idea is to let a user delete a profile because it is no longer needed. 

Today, a user can remove a profile which removes it from the Zowe Explorer UI but the profile remains stored in the .zowe > profiles folder. 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/3207260/69658498-4d604300-104a-11ea-976e-fca56657561c.png">

**Comment by crawr** [comment]
@jelaplan For the function to delete profiles permanently,
Instead of the following options, 
1. via dropdown context menu
2. via trash icon near the profile

I would like to implement it
3. via a separate "Command Palette" option. (via `Ctrl+Shift+P` in Windows)
![delete](https://user-images.githubusercontent.com/45845502/78357790-5641c200-75b2-11ea-80e3-849b6cad80bb.PNG)

The next step would be to choose the profile from the list
![select](https://user-images.githubusercontent.com/45845502/78357791-56da5880-75b2-11ea-8022-6467fce878b3.PNG)

The idea is just to declutter the tree as I don't see myself using this option as often as Search or Create Dataset.

**Comment by jelaplan** [comment]
@crawr I prefer option #1. You might not be surprised that I'm not a fan of burying it in the command palette with option #3. I agree that option 2 is overkill because it isn't something used often. In the context menu, we have the Issue Command  option and that is also available in the command palette. I'd like to see Delete Profile done the same way.  

![Delete Profile](https://user-images.githubusercontent.com/3207260/78581106-68fe0600-7801-11ea-9bdc-093809ae272c.png)

The Figma version. 
https://www.figma.com/file/9iSLJIpwD9m6pWzFLjFbym/Explorer?node-id=1190%3A2486

**Comment by zdmullen** [comment]
From the review today, shall we consider renaming "Remove profile" to "Hide profile", to help differentiate for the user what Delete does?

**Comment by jellypuno** [comment]
tagging @jelaplan

**Comment by jelaplan** [comment]
I missed the review. I asked Vaclav for the recording. Remove profile has been confused with delete profile in 2/3 usability tests I've run so yes, it seems a poor name. Hide profile seems much better.

**Comment by jelaplan** [comment]
@crawr, did you add a context menu entry?

**Comment by crawr** [comment]
> @crawr, did you add a context menu entry?

@jelaplan Yes, I did.

Based on the comments, the new context menu for Data Sets and USS tree profiles will be: 

![image](https://user-images.githubusercontent.com/45845502/79309091-06d88b80-7efa-11ea-8b4b-77de422cd300.png | width=100px)

**Comment by jellypuno** [comment]
Hide Profile makes sense to me.
