### ISSUE TITLE
Append Filter when Adding a new Dataset

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#385]
When creating a data set, it would be great to append a filter so that it shows up in the list and the user can begin working with it immediately. Otherwise, the user gets no feedback other than no error that the data set was created successfully. If the user wants to immediately begin working on that data set, she has to rerun the filter. 

The system supports appending filters with a comma when creating filters. My idea is to take the current filter and append another filer and rerun it so that both the current filter contents appear and the new data set.

**Comment by katelynienaber** [comment]
I call it!

So right now I have the new data set showing up in the list. But after creating the data set, the profile is refreshed, and the existing filters are erased from the list.

And I will work on this Monday.

**Comment by katelynienaber** [comment]
Quick question...should we add the new dataset to the current filter? Or just replace the old filter and only show the new dataset?

Because the newly-added dataset will not automatically appear at the top of the list...for example if I create `Z40641.NEW.PDS.TEST8`, it appears in the middle of the list.
![image](https://user-images.githubusercontent.com/58596139/70909830-98002a00-200e-11ea-83e1-de877886c445.png)

In a large list of datasets, it might not be obvious that the new set was already in the list...

**Comment by Morridt** [comment]
In my opinion it should be created as you've done above and then "selected".
(and thanks to this post I did not realise you could add more than 1 statement to a filter)

**Comment by katelynienaber** [comment]
Closed in pull request [#429](https://github.com/zowe/vscode-extension-for-zowe/pull/429)
