### ISSUE TITLE
Code concern from Handle issue 352: Prompt Credentials for Favorites 

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#413]
This was missed during recent reviews but code was added recently to extension.ts that may have undesirable affects.
`export async function openPS(node: ZoweNode, previewMember: boolean) {
    const datasetProvider = new DatasetTree(); // Why are we creating a new tree? `

The reference is used later to 
       `await datasetProvider.refreshElement(node);
       await datasetProvider.refresh(); `

Does anyone recall why this was made. Instantiating another tree could have unknown consequences on the real DatasetTree and I see no rationale for refreshing

**Comment by jellypuno** [comment]
Hi @Colin-Stone ,

So I tested this one, the reason for
```
 await datasetProvider.refreshElement(node); 
await datasetProvider.refresh();
```
is to refresh the Dataset Tree so if I open the profile, the credentials will not be prompted anymore.

So the scenario is:
_Step1:_ I added a dataset in my favorites, I am prompted to enter the credentials. I can open it after that.
_Step2:_ I added the profile in my dataset tree afterwards, I am prompted for profile again. 

![Issue413](https://user-images.githubusercontent.com/45042840/70989323-b70cc380-20c3-11ea-8082-3048169ba16d.gif)

If I add the refresh, I am not prompted in Step#2. I hope I explained it well.

The reason I have a new DatasetTree is because I need to call refreshElement(). Is there a different way to call this function?

**Comment by Colin-Stone** [comment]
Thanks for looking at this so quickly Jelly.. I can understand the strategy now. I am concerned because the singleton DatasetTree had already been instantiated and now we have a second instance. It must be that somehow VSCode takes care of this for us. 

If the datasetProvider is available for the OpenPS call then yes it could be passed. 
Thanks again for looking so quickly

**Comment by jellypuno** [comment]
#414

**Comment by zFernand0** [comment]
Should this issue be closed?

**Comment by Colin-Stone** [comment]
> Should this issue be closed?

I think so. If you see the conversation in #414 the singleton datasetProvider can be included in the command declaration in extension.ts

**Comment by zFernand0** [comment]
Thanks! 👍
