### ISSUE TITLE
Provide Save option and Submit Job option from text editor window

### ISSUE THREAD

**Issue by ghost** [zowe/vscode-extension-for-zowe#426]
From an editor view of a zOS data set member, or a USS member, in Zowe CLI, running on VSC, provide the ability to save the changes to it, or to submit it to zOS without having to move away to another part of the screen. If a Save option and a Submit to zOS option can be added in the list that appears when the right mouse button is clicked, then that would be useful. Both these are available in zOS Explorer, and that seem to me to be a more natural way to carry out these operations. Obviously if the file in the editor is not a piece of JCL that the submit option should be rejected, as it currently is if this is done from the DATA SETS view.

**Comment by jellypuno** [comment]
Kinda similar to #411

**Comment by JillieBeanSim** [comment]
I believe we can bring in a right-click action to Submit local file as a new optional API for extenders.  zOSMF has this capability via CLI, we just need to adopt that.
For Saving files, since it is local we may be able to introduce a right-click action for Upload to MVS or Upload to zUNIX.

This story should be split into 2 since it asks for multiple things, I will create the new story for Submitting local file since I plan to work on that first and that will keep this open for the second part if planned.
