### ISSUE TITLE
Cannot create a new profile with the "plus" button

### ISSUE THREAD

**Issue by zimlu02** [zowe/vscode-extension-for-zowe#427]
1. Install Zowe Extension in VSC on clean Mac  (no Zowe CLI installed)
2. Click on the '+' button to create a new profile
3. error message "command 'zowe.addSession' not found"
4. the profile cannot be created using the UI

**Comment by zimlu02** [comment]
![VaseksMac2](https://user-images.githubusercontent.com/38490125/71189007-5d9ec300-2282-11ea-9168-b0d531cddb7e.png)

**Comment by jellypuno** [comment]
I am not experiencing the exact error but hopefully fix from #432 will solve this.

**Comment by jalel01** [comment]
@zimlu02 could you let us know if this is still an issue on v1.1

**Comment by zimlu02** [comment]
I can still reproduce it with v1.1

**Comment by jellypuno** [comment]
> I can still reproduce it with v1.1

@zimlu02 Please install [NodeJS](https://nodejs.org/en/download/) then try again.

**Comment by jelaplan** [comment]
I am working with Susie Robson on usability testing of the Zowe Extension. Trying to get her up to speed and she has the same problem as @zimlu02. I looked in her Finder and there is no .zowe folder. I went ahead and renamed my .zowe folder and tried to restart VS Code. I get different errors but I'm not able to create a connection / profile. 

Here is the error messages I get when trying to click the + icons. 
![image](https://user-images.githubusercontent.com/3207260/72268599-16d98a00-35f0-11ea-8e53-cb4ed70c4d3d.png)

Here is what happens to me when I try to start VS Code without a .zowe folder. I also went into the Zowe Configuration settings file and removed history of searches, profiles, etc. I get the same kind of errors. 
![image](https://user-images.githubusercontent.com/3207260/72268703-50aa9080-35f0-11ea-9961-2a8c288a255d.png)

![image](https://user-images.githubusercontent.com/3207260/72269403-8734db00-35f1-11ea-86ee-926c753876f7.png)

**Comment by jellypuno** [comment]
@jelaplan ok. this is a different issue. This is what i would suggest.

1. Make sure that you have NodeJS Installed. To verify, open the terminal and type `node -v` and `npm -v`
2. Delete the .zowe folder you manually created.
3. Close VSCode
4. Open VSCode. If Zowe Explorer is installed the _.zowe folder will be created automatically._
5. **Wait** until the _No Default zosmf profile_ message appears or the word **Favorites** appears in the panels **before clicking anything.** Please note that VSCode is initializing and if you start clicking the error message _command zowe.something not found_ will appear. If this happens then you will experience errors because the extension did not initialize correctly.

**Comment by zimlu02** [comment]
Nodejs fixed the problem! Thanks

**Comment by jelaplan** [comment]
I can have Susie install NodeJS. I was under the impression that new users would need only install VS Code and the Zowe Explorer extension. That that would bring Node with it. So, I'll work with Susie this afternoon to install Node and I'll report back.

**Comment by jelaplan** [comment]
@jellypuno that worked. We installed Node on Susie's machine and all is well.

**Comment by zFernand0** [comment]
FYI, 
https://github.com/zowe/vscode-extension-for-zowe#software-requirements
