### ISSUE TITLE
Securely stored credentials not being read

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#507]
Zowe Explorer is no longer reading the credentials from the secure credential store. Zowe Explorer is working for me with version 1.1.0 but not with version 1.2.0 or 1.2.1.

![image](https://user-images.githubusercontent.com/35504792/73997812-b6055d80-49b3-11ea-9274-054cf4ea9159.png)

**Comment by Colin-Stone** [comment]
Tested with the SCS plugin v4.0.0. Can you confirm that you removed your .zowe/profiles folder before doing this?.

**Comment by MikeBauerCA** [comment]
I saw this issue happen with both the `@latest` and `@lts-incremental` version of the secure credential store plugin. Why would I need to remove the `.zowe/profiles` folder? I have many profiles and I would not want to recreate them.

**Comment by Colin-Stone** [comment]
I agree but that was always the brief I had was that the .zowe/profiles folder had to be removed because by not doing so the profiles would fail to load due to conflict. 
I was asking to confirm if what you are seeing is what we already knew and would need to document for or if it is a separate issue.

**Comment by MikeBauerCA** [comment]
It appeared that Zowe Explorer was unaware that the Secure Credential Store plugin for Zowe CLI was installed. We tried to create a profile through the Explorer and it worked, but the creds were stored in plain text.

**Comment by Colin-Stone** [comment]
The appropriate Credential key is needed within the Explorer that describes the key prefix that is in use. 
<img width="870" alt="image" src="https://user-images.githubusercontent.com/30794003/74013016-76bf1880-4983-11ea-8402-5c994a2317af.png">
I have been intending to blog about this but basically the default is set to the v4 SCS plugin so if installed  (i.e. imperative.json has the appropriate keys set) it would work straight out of the box. Using the default keytar basic zowe/cli solution is mentioned here also. The earlier SCS version used a key with a `@Broadcom-plugin` reference that I thought we would prefer not to have in the description

**Comment by MikeBauerCA** [comment]
The Explorer previously worked with the SCS CLI Plugin without requiring additional configuration. As the SCS plugin is being contributed to `@zowe-v1-lts`, the recommended Zowe install will include the CLI, SCS plugin, and Zowe Explorer. These components should integrate seamlessly together. 1.1 to 1.2 resulted in a breaking change that may need to be reverted. It is great that the Explorer can be used standalone but folks looking to get the most value out of the Zowe solution will be using these components together.

**Comment by Colin-Stone** [comment]
> The Explorer previously worked with the SCS CLI Plugin without requiring additional configuration. As the SCS plugin is being contributed to `@zowe-v1-lts`, the recommended Zowe install will include the CLI, SCS plugin, and Zowe Explorer. These components should integrate seamlessly together.

That is the case since the default is set to work with what we know is the key used by the v4 SCS plugin. This seemed to me the most common configuration. 

> 1.1 to 1.2 resulted in a breaking change that may need to be reverted. It is great that the Explorer can be used standalone but folks looking to get the most value out of the Zowe solution will be using these components together.

Totally agree. My investigations were to look at what appears in the credentials store. For the keytar solution the value corresponded to the name of the cli module which was `@zowe/cli` for v1.1 and/or 1.2 it was specifically `Broadcom-plugin`. There is a possibility that the imperative.properties file could give me a clue but it would only be a partial clue with three possibilities. Hence the solution was to setup for what I perceived would be the most common implementation

**Comment by MikeBauerCA** [comment]
Thanks, maybe @zFernand0 could give this a try with both the `@latest` and `@lts-incremental` versions of the SCS CLI plugin and report his findings. Be sure to create the profile first with the CLI plugin and then try to use the Zowe Explorer.

**Comment by zFernand0** [comment]
This should be fixed by #531
