### ISSUE TITLE
Zowe 1.2.1 does not activate when ~/.zowe directory is not present

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#514]
In Zowe Explorer v1.1.0 we had a ProfileLoader class that would actually spawn a node process to run the imperative main from node_modules to basically run Zowe CLI to create the .zowe directory in the user’s home directory and if already present read the profiles already available.  This was useful for users who do not have Zowe CLI installed as they could just use Zowe Explorer without installing the CLI. 

I see that this code got removed in this PR https://github.com/zowe/vscode-extension-for-zowe/pull/400. So now when I install Zowe Explorer without having a ~/.zowe directory activation of Zowe Explorer even fails. The only workaround it seems is installing Zowe CLI and calling any command.

![image](https://user-images.githubusercontent.com/4391934/74381171-d2344080-4d9f-11ea-80c4-0c873110846e.png)

**Comment by phaumer** [comment]
I created this PR as a quick work-around using the previous technique of initializing the .zowe directory. I am hoping there is a different way. See the commented out lines of code in the PR, which was the other way I tried this unsucessfully.

**Comment by Colin-Stone** [comment]
The spawn function was originally added to profile management because of issues loading a profile that used a security mechanism such as keytar. It required that the original cli node app to load the keys correctly. With the keytar implementation complete the spawn function was considered redundant and hence all mechanisms around it removed.
It sounds that this function served a secondary purpose of instantiating the .zowe folder if CLI was not already installed. 
I'm not sure we need to spawn a process to achieve this but need to reinstate code in some way to satisfy the issue at least temporarily

**Comment by tjohnsonBCM** [comment]
@phaumer Sorry, I didn't understand exactly what the issue was when initially discussing this on Slack.

It appears that the extension is only expecting the `.zowe` folder to exist in order to access `~/.zowe/settings/imperative.json`. I believe the extension is already handling the case that the `~/.zowe/profiles/zosmf` folder may not exist when creating a profile.

We should be able to fix this by setting `imperativeIsSecure` to false if the `settings.json` file doesn't exist.

**Comment by tjohnsonBCM** [comment]
Previous comment is incorrect, the `~/.zowe/profiles/zosmf` folder is also an issue. Discussed this with @zFernand0 and we should be able to make a patch in @brightside/core to allow a more ideal fix.

**Comment by tjohnsonBCM** [comment]
Created an alternate fix in this branch: https://github.com/zowe/vscode-extension-for-zowe/compare/fix-514

It works without spawning a process, but requires that this PR be merged first: https://github.com/zowe/zowe-cli/pull/671

**Comment by Colin-Stone** [comment]
So we have Peter's quick work-around, my reworked work-around and a proper fix provided we include the relevant cli merge. I prefer Timothy's proper fix if we can turn it around quick enough. Could this be targetted for the v1.3 release which would include the switch to @zowe also?.
