### ISSUE TITLE
Error running command zowe.pattern: Running the contributed command: 'zowe.pattern' failed.. This is likely caused by the extension that contributes zowe.pattern.

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#569]
I am experiencing this error when I am running Zowe Explorer. Can somebody please help me? 

![Capture](https://user-images.githubusercontent.com/45042840/75675725-fb9e0900-5c87-11ea-81b2-0c855e3ea3b9.PNG)

- I have SCS installed:
-- pluginName: @zowe/secure-credential-store-for-zowe-cli
 -- package: @zowe/secure-credential-store-for-zowe-cli
 -- version: 4.0.1
 -- registry: https://registry.npmjs.org/
- I executed `zowe scs u` so all profiles are secured
- I updated the setting.json in VSCode:
![Capture](https://user-images.githubusercontent.com/45042840/75675690-e4f7b200-5c87-11ea-9d26-3a2bcc498486.PNG)

Am I missing something?

**Comment by tjohnsonBCM** [comment]
Not sure what's causing the `zowe.pattern` error, although the message says "this is caused by the extension" I don't believe it's related to the Secure Credential Store.

Based on the version of the SCS plugin you have installed, the value of "Zowe Security: Credential Key" in VSCode settings should be `Zowe-Plugin` instead of `@zowe/cli`. You can also leave the setting blank/undefined and it will default to `Zowe-Plugin`, contrary to what the documentation for the setting says.

We should update that documentation to convey the current behavior of the setting (probably a separate issue).

**Comment by Colin-Stone** [comment]
@jellypuno Is this still an issue?. Should have been fixed by https://github.com/zowe/vscode-extension-for-zowe/pull/573

**Comment by jellypuno** [comment]
I will test it today

**Comment by jellypuno** [comment]
It's okay now.
