### ISSUE TITLE
Zowe Explorer Icon Update

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#615]
The Zowe Explorer icon needs to be updated to the new standard: https://github.com/openmainframeproject/artwork/blob/master/examples/active.md#zowe-logos

This update should be on both the marketplace and in VSCode itself (on the sidebar).

Tagging @jelaplan for his awareness

**Comment by stepanzharychevbroadcom** [comment]
Added new icons in https://github.com/zowe/vscode-extension-for-zowe/pull/624

**Comment by stepanzharychevbroadcom** [comment]
@jmertic I updated the SVG icon to get rid of the arifact, which was caused by 2 paths being inappropriately combined. I added new version which matches the old one, but uses only 2 grouped paths.

**Artifact:**
![Screenshot 2020-03-13 at 15 05 00](https://user-images.githubusercontent.com/60000150/76628382-eacd7d00-653c-11ea-9396-c46f07bafbfb.png)

**New Icon:**
[zowe-icon-white-new.svg.zip](https://github.com/zowe/vscode-extension-for-zowe/files/4329975/zowe-icon-white-new.svg.zip)

**Comment by MikeBauerCA** [comment]
Thanks @stepanzharychevbroadcom! This issue is also visible on [zowe.org](https://www.zowe.org/) today @jmertic 

![image](https://user-images.githubusercontent.com/35504792/76628817-b72a2d00-6513-11ea-8080-4a13178747ee.png)

**Comment by jmertic** [comment]
Let me have the LF CS team review and get back to you with an updated version. Thanks for catching this!

**Comment by MikeBauerCA** [comment]
Thanks @jmertic. We are updating the icon with our next drop. If the LF CS team comes back with a different version than the one @stepanzharychevbroadcom proposed, let us know and we will publish a fix for it.

**Comment by zFernand0** [comment]
Icon updated in `1.3.1`

**Comment by jmertic** [comment]
@zFernand0 - Can you validate the zowe.org has the fixed logo? If so we get over fixed icon svgs

**Comment by zFernand0** [comment]
Icon seems to be fixed by https://github.com/zowe/zowe.github.io/commit/0774855d02751d4ef11a14d1f6d866203a454ba2.

See: https://github.com/zowe/zowe.github.io/blob/master/assets/img/zowe-logo.svg

![image](https://user-images.githubusercontent.com/37381190/77318101-d464b580-6ce2-11ea-89bf-f18482e5354c.png)
