### ISSUE TITLE
z/OS Jobs part of the extension is missing Zowe: "Add profile" action

### ISSUE THREAD

**Issue by t-o-m-e-k** [zowe/vscode-extension-for-zowe#62]
Currently z/OS jobs extension is working only with the default profile. Changing profile requires setting new default profile and restarting VS Code.

Data sets and USS part of the extension allow to add another profile. It would be nice to have same functionality when working with Jobs.

I have also noticed that icons for "Zowe: Add profile" action are inconsistent. For "Data Sets"  it's plus sign (+) and in case of "Unix System Services (USS)" it is ellipsis (…) for more actions.

**Comment by Colin-Stone** [comment]
Thanks for spotting this and sorry we dropped the ball or the graphic images to be exact. The USS ellipses is a relatively quick fix, so expect a new version sometime today. You will notice we are continuing to consolidate the views into one container and still have some work to do. What would be your opinion if the Datasets/USS/Jobs views were combined under one view?. In effect making the profile the root of the tree rather than the view title (Jobs, USS etc)

**Comment by Colin-Stone** [comment]
Fixed as part of single view container. Version 0.14.0

**Comment by t-o-m-e-k** [comment]
I like the idea of having all ZOWE related views in one container, as well as having the profile as a root.

Have you considered an option of making job prefix and owner information visible?
Similar to "SET DISPLAY" in SDSF.  I have it always turned on. It's much easier to correct any typos in my selection criteria. 
Maybe a text box for each filter?
