### ISSUE TITLE
feat: improve messaging for confirmation dialogues

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#701]
### Current behavior

For delete actions on Data Sets, USS Files, and Profiles, we have the following quick pick options:

```
Are you sure you want to delete <item>
- Yes 
- No
```

Meanwhile, for opening binary USS files, we have the following wording:

```
Failed to open file as text. Do you want to try with re-downloading it as binary?
- Yes, re-download 
- No
```

### Proposal

Standardize and improve the messaging for confirmation dialogues.

```
Delete <item type> <item>? This will permanently remove it from your system.
- Cancel
- Yes, delete
```

```
Failed to open file as text. Re-download file as binary?
- Cancel
- Yes, re-download 
```

Reference: [Are you sure you want to do this? Microcopy for confirmation dialogues](https://uxdesign.cc/are-you-sure-you-want-to-do-this-microcopy-for-confirmation-dialogues-1d94a0f73ac6)

**Comment by zdmullen** [comment]
An additional reference that I had seen is here: https://medium.com/@wutronic/which-to-choose-cancel-ok-ok-cancel-or-yes-no-ec119861eb9b

**Comment by crawr** [comment]
Tagging @jelaplan

**Comment by jelaplan** [comment]
This is good work. I like the suggestions and Zach's article is helpful. This kind of thing has been argued for a long time and I generally like the way Macintosh does it with explicit labels and not so much Windows which uses ok / cancel because the user can then just look at the choices without reading the labels. I would put the choices in reverse order because it is faster to access with an arrow key but you could argue it either way.  I'd also not use the term Yes because that forces the user to think about what yes means (it is a small thought but that little bit of cognitive friction is unwelcome). The term 'delete' matches what they chose on the menu so it is easily matched in their memory which is a no-thought kind of thing - sort of like we see in a lot of children's games.  Rephrasing of the label is also good because it gets right to point and adds the explanation secondarily. 

- Delete
- Cancel

- Re-download
- Cancel
