### ISSUE TITLE
cleanup of recall for setting.json

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#746]
Due to added changes in addRecall toUppercase(), Some new data added in recall:[] are not deleted properly.

**Comment by katelynienaber** [comment]
So this is due to this line: https://github.com/zowe/vscode-extension-for-zowe/blob/2d09a64ce3c90b2e4e84e54a6f4700e0ebc926b3/src/PersistentFilters.ts#L106

I added this line because the addRecall() function could receive a path with any sort of capitalization, and this should not cause addRecall() to add a duplicate item to the recall array.

I would like to leave it this way, otherwise we will need to standardize capitalization in all paths...

**Comment by jellypuno** [comment]
@katelynienaber Yah. no worries. with PR #631 this issue is actually fixed 😄
