### ISSUE TITLE
Unit Tests - Mocking concepts

### ISSUE THREAD

**Issue by stepanzharychevbroadcom** [zowe/vscode-extension-for-zowe#764]
Currently in Unit Tests prevails the following way of function mocking:
```javascript
const unlinkSync = jest.fn();
Object.defineProperty(fs, "unlinkSync", { value: unlinkSync });
```
So we create _named mock function_ and use it in actual test to do `mockReturnValue` and etc. The fundamental problem of this approach is in lengthy tests it may be very hard to understand what this function actually represents and you have to search through file for the actual place definition.
Suggestion is to eliminate those named functions as a concept and use the following format:
```javascript
Object.defineProperty(fs, "unlinkSync", { value: jest.fn() });
```
As a result you will need to use `fs.unlinkSync.mockReturnValue` in actual test what increases readability a lot. The only problem which we have with this approach is **TypeScript**. To be specific: TS won't understand that we've overwritten the function in some module and still will treat it as an original implementation. To prevent it I suggest the following structure:
```typescript
const mocked = (fn: any): jest.Mock => fn;
```
It basically accepts function and returns it back overriding type to `mock`. (idea is borrowed from [here](https://github.com/kulshekhar/ts-jest/blob/master/src/util/testing.ts))

Actual example of this approach in action can be found [here](https://github.com/zowe/vscode-extension-for-zowe/blob/refactor-dataset-tests/__tests__/__unit__/dataset/actions.unit.test.ts#L47).
Please, let me know about thoughts and concerns about the approach.

**Comment by jellypuno** [comment]
Personally, these are the concerns that I have about this new way of mocking:

- It will take a lot of work to change all the tests to adhere to this new programming standard. This is not part of our deliverables. This is technically re-coding all test and not just re-factoring it. Even if it takes just one day to re-code all test, it will take several days to review it, revise it and approve it and this will lead to a delay in our objectives.  And we have lots on our plate already. 

- This does not adhere to the global programming standards or coding style in the Zowe community and possibly the Open Source community. If I am a new contributor to Zowe Explorer and I have been contributing to Zowe-CLI or Zowe Desktop, this is a new way of programming standard that I need follow. Rather than to contribute based on what I know, I have to change  the coding style. 

If you check the test in these repositories, you will see that the coding style is the same. It is readable and similar to each other. 

[**AWS Toolkit**](https://github.com/aws/aws-toolkit-vscode/tree/ab650f54d0a4526aadcbff2979136f27ba735717/src/test)

[**Zowe-CLI**](https://github.com/zowe/zowe-cli/tree/master/__tests__)

[**Zowe Desktop**](https://github.com/zowe/explorer-uss/tree/master/tests)

**Comment by stepanzharychevbroadcom** [comment]
@jellypuno I understand your concerns. I have 2 points:
1. Me and Katelyn will eventually revisit all tests during the refactoring. And when I fix tests I actually recode them anyways to match other standards;
2. I totally get the thing about other repos, but big things should start with something small. I think that longer definitions will help newcomers read tests better and as a result understand it better with very low cost of additional concept there;

**Comment by jellypuno** [comment]
> Me and Katelyn will eventually revisit all tests during the refactoring. And when I fix tests I actually recode them anyways to match other standards;

Let me tag @zdmullen with this. Because this does not just affect you. It affects our team.

**Comment by katelynienaber** [comment]
> > Me and Katelyn will eventually revisit all tests during the refactoring. And when I fix tests I actually recode them anyways to match other standards;
> 
> Let me tag @zdmullen with this. Because it affects our team.

We gotta decide on this ASAP because it is affecting our ability to merge the refactored tests.

**Comment by katelynienaber** [comment]
In my opinion...

PROS:
- Mocking in this way will reduce confusion about what jest function is used to mock what extension function
- Reduces size of test files

CONS:
- We have to redo all the tests
- We will all have to relearn how to mock some things (like the trouble I had today with mocking a static class function in the new way)

TBH the minus of everyone having to change how they do things seems like a pretty big minus, time-wise. And also I don't want to work on refactoring tests forever...this will take a long time to fix.

It does make things somewhat clearer when reading the code, but not so much so that it's worth the time spent learning how to do it for some special cases...

**Comment by stepanzharychevbroadcom** [comment]
@katelynienaber Technically I presented this idea in the very beginning and nobody was against it. I think if not as a standard we still should allow this way and give contributors right to choose.

**Comment by katelynienaber** [comment]
@stepanzharychevbroadcom What if one test file uses both mocking methods for a single function?

**Comment by stepanzharychevbroadcom** [comment]
@katelynienaber Then the code shouldn't be merged. If 1 function is mocked in 2 different ways then it means it's a mistake on the side of the implementation, as if you did 2 different variables which handle the same value.

**Comment by katelynienaber** [comment]
In order to avoid mocking twice, I might have to do this:
```
    it("Tests that node.refreshUSS() works correctly for dirty file state, when user didn't cancel file save", async () => {
        ussFile.mockResolvedValue(response);
        mocked(node.isDirtyInEditor).mockReturnValueOnce(true);
        mocked(node.isDirtyInEditor).mockReturnValueOnce(false);

        await node.refreshUSS();

        expect(ussFile.mock.calls.length).toBe(1);
        expect(showTextDocument.mock.calls.length).toBe(2);
        expect(mocked(vscode.commands.executeCommand).mock.calls.length).toBe(2);
        expect(node.downloaded).toBe(true);
    });
```

Not only is it messy, but I have to keep track of which functions are mocked in each way.

Therefore I will still have to look up the mock definitions.

And somebody adding tests to this file will have to know how to mock both ways, if they want to use a function you have already mocked with the new method.

**Comment by katelynienaber** [comment]
Can we close this issue??

**Comment by zdmullen** [comment]
I think that this can be considered close. I refer everyone to the guidance doc that @stepanzharychevbroadcom created here: https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Unit-Test-Structure
