### ISSUE TITLE
Provide better error message for deleted profile in favorites

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#791]
> The only thing I am not sure is this part of the error message:
"To resolve this, you can create a profile with this name, or remove the favorites ..."
>
> If the user creates another profile with the same name but points to a different place, it can possibly bring confusion. Wouldn't it be just safer to leave out this part of the message and keep just the advice to drop the missing favorite item...?

_Originally posted by @zimlu02 in https://github.com/zowe/vscode-extension-for-zowe/issues/455#issuecomment-624783184_

**Comment by zFernand0** [comment]
@jelaplan any thoughts?

**Comment by jelaplan** [comment]
@zFernand0 I'm not sure I fully understand what is happening. I do realize people are trying to use a favorite that relies on a delete profile and they get an error message. The suggestion to just advise to delete the favorite without telling them to repair their connection profiles is ok. But the reason is that it is simple to understand and doesn't present complicated advise about repairing things.  It seems farfetched that someone would create a connection with the same name and a different LPAR. A radical idea would be to delete any dependent favorites when deleting a profile and get out of the business of creating elaborate error messages :)

**Comment by lauren-li** [comment]
Now that the UX flow for removing favorited profiles has been updated, this error message can also be updated to just advise the user to use Zowe Explorer's UI to remove the deleted profile from the Favorites section.

(Full current error message, for reference):
<img width="455" alt="Screen Shot 2021-01-13 at 4 46 18 PM" src="https://user-images.githubusercontent.com/45975633/104514482-53ebaa00-55bf-11eb-875b-ee6c485735f9.png">
