### ISSUE TITLE
Support duplicating data sets

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#871]
**Problem**
ZE supports creating a data set. But, it is a common practice on MF for users to duplicate existing data sets rather than creating from scratch. This practice is common because names can be quite long and it is trouble to key in again plus there can be series of data sets that all need the same name - JCL lib, assemble lib, copybook lib, all same name expect the last piece.

The ZE interface does NOT presently allow copying data sets which would be one way to duplicate a data set. 

Duplicating is sometimes referred to as cloning data sets. So maybe that is the more appropriate term than duplicate.

**Solution**
1. Implement the copy data set feature. 
2. Support an explicit duplicate/clone feature for data sets.

**Comment by venkatzhub** [comment]
@jelaplan - Is this about copying datasets OR allocating/creating a data set (which will be empty) that matches something that is there?

**Comment by zFernand0** [comment]
> @jelaplan - Is this about copying datasets OR allocating/creating a data set (which will be empty) that matches something that is there?

For dataset-like feature, see #904

**Comment by jelaplan** [comment]
@venkatzhub yes and no. The idea is to let people copy a file whole or to copy the properties and paste into a new data set. I'm familiar with this being referred to as allocate all.

**Comment by venkatzhub** [comment]
@jelaplan - I would prefer handling this as two functions: 

Allocate Like:  allocate a dataset with the same exact properties as the one I as a user am pointing to/or selected)

Copy of an entire dataset: Allocate a dataset with the same properties as the Source (dataset user wants to copy) and copy all the members from the source dataset to the newly allocated one. For this one, a clear definition of what the "Target" node where the user can execute the Paste action is important. By that, I mean you cannot Select a Dataset member or another dataset as a target and execute Copy on that (since a PDS cannot contain a PDS).

**Comment by jelaplan** [comment]
Fernando, thanks for pointing to #904 which addresses Allocate Like.

@venkatzhub WRT to copying contents, we today can copy a member from one dataset to another or copy that member into the same dataset which amounts to a duplicate. But the interface doesn't allow duplicating a dataset, that is copy it.

**Comment by JillieBeanSim** [comment]
Allocate like is in place. closing
