### ISSUE TITLE
Allow Zowe Explorer to function without OSMF, by instead using zos-ftp-for-zowe-cli plugin

### ISSUE THREAD

**Issue by Cris70** [zowe/vscode-extension-for-zowe#994]
**Is your feature request related to a problem? Please describe.**

I am working in a mainframe environment where osmf is not available. I have however installed and configured zowe-cli with the zos-ftp-for-zowe-cli plugin, which is working nicely.

**Describe the solution you'd like**

I would like to be able to use Zowe Explorer in conjunction with a zftp profile, instead of a zosmf profile, even if that would result in reduced functionality.

**Describe alternatives you've considered**

There are no known alternatives for working with mainframe datasets through an ftp connection. Other ftp VSCode extensions do not work with the mainframe.

**Comment by zdmullen** [comment]
Hi @Cris70! Have you seen the FTP extension that is built on top of Zowe Explorer? Find out more information about it here: https://github.com/zowe/zowe-explorer-ftp-extension

**Comment by Cris70** [comment]
Hey @zdmullen thank you very much for your pointer!!
However, I'm not sure I understand how to use that extension. I have the Zowe Explorer extension installed, now what do I have to do to add this zowe explorer ftp extension? I see no way of installing it in VSCode, and there's no release available in the github page. Do I have to build it myself to use it?

**Comment by zdmullen** [comment]
I do believe that yes, you have to build it to use it, following the directions in the readme file. That said, I'll just suggest that perhaps  @zFernand0 or @lauren-li could weigh in on how to use the extension (or others).

**Comment by lauren-li** [comment]
@zdmullen is correct - at this time, you have to build the Zowe Explorer FTP Extension in order to use it. Directions on building can be found here: https://github.com/zowe/zowe-explorer-ftp-extension#build-this-extension. (You will need to have Yarn installed in order to build it.) Once the `.vsix` file is generated through these instructions (i.e. after the step to run `yarn package`), you can then install the Zowe Explorer FTP Extension from the `.vsix` file:

- In VS Code's **Extensions** view, click the `...` icon (green box in the below screenshot), then click "Install from VSIX...", and use the file picker that pops up to navigate to and select the `.vsix` file you generated. Once you you have installed Zowe Explorer FTP Extension in this way, you should be able to access your zftp profile and use it in the **USS** section of Zowe Explorer.
<img width="530" alt="Screen Shot 2020-08-28 at 10 57 57 AM" src="https://user-images.githubusercontent.com/45975633/91583598-74241080-e91f-11ea-87ed-5d23dd835c81.png">


@zFernand0 @phaumer Perhaps we could consider making a release tag for the Zowe Explorer FTP Extension that has a downloadable `.vsix` file attached to it? This would make it easier for users to get the extension.

**Comment by Cris70** [comment]
@lauren-li thank you for the detailed instructions. I have built and installed the extension, which is working.
However, it seems it only works with USS files, not with z/OS datasets. Is it limited to USS? If so, it really is not very useful... I could have used one of the other FTP extensions to work with USS files.
From the command line I can use zowe-cli to access to z/OS datasets. e.g. the `zowe zos-ftp list ds SIGDC.**` command lists all my datasets (SIGDC is my userid)...

**Comment by lauren-li** [comment]
@Cris70 Thank you for trying the Zowe Explorer FTP extension. Currently, it only works with USS. However, the functionality could be expanded to support data sets, as well. This would be a great issue to file under the [Zowe Explorer FTP Extension’s repository](https://github.com/zowe/zowe-explorer-ftp-extension), as that would indicate to the development team that there is community interest in the feature, and keep it on their radar.

**Comment by Cris70** [comment]
Once again thank you @lauren-li. I have just finished [adding the issue](https://github.com/zowe/zowe-explorer-ftp-extension/issues/10) as per your suggestion.
