### ISSUE TITLE
Confirmation before submitting a job

### ISSUE THREAD

**Issue by gcartier94** [zowe/vscode-extension-for-zowe#998]
**Is your feature request related to a problem? Please describe.**

Recently I was working with some of the JCL on my LPAR using the Zowe Explorer. When I decided to test it I've noticed that I've accidentally submitted the wrong job. Fortunately, I was working a controlled environment and that had no impact on my system. 

**Describe the solution you'd like**

It would be very helpful if the Zowe Explorer could prompt for a confirmation before submitting the currently selected JCL since is very easy to misclick and select the wrong member of the PDS instead.

**Comment by zdmullen** [comment]
Thanks for opening the issue, @gcartier94. We've discussed it as a squad, and feel that there is further analysis needed because we should investigate confirmation messages more in general and the ability to potentially disable/enable them in settings. 

@jelaplan and Ilya, could you consider this from the UX point of view?

**Comment by fbeyl** [comment]
This is an important improvement! Rightclick and click submit without seeing and confirming what will be submitted is easy and fast but potentially dangereous especially for highly authorized users like sysprogs.

**Comment by IlyaKreynin** [comment]
If the error is easy to make, difficult to detect, and can have real consequences, a settings-toggleable confirmation message makes sense! The option to toggle confirmation messages off should also exist within the confirmation messages themselves.

To potentially reduce errors without confirmation messages, we could change the text of the action from "Submit Job" to "Submit *NAME OF JOB* As Job" or something to that effect. This gives users another chance to see what is actually being submitted without adding clicks. This change could be implemented with or without confirmation messages - should help either way!

**Comment by zdmullen** [comment]
Note: this could also be an option that you could toggle in the settings.json.

**Comment by zdmullen** [comment]
@jelaplan to reach out to guillerme!

**Comment by jelaplan** [comment]
I will reach out to Cartier and talk to him about it. Submitting the wrong job is clearly a mistake to be avoided and the intention seems good but I suspect that a popup that asks are-you-sure is something to blow past so may offer little in the way of prevention. At the same time, an are-you-sure prompt is liable to be bothersome to some people. I like Ilya's idea to echo the job name in the menu command. But, is the job name sufficient and will people stop to read? The popular book "Don't Make Me Think" would indicate not. We could make the interaction more intentional by asking the user type in the job name. We could ask them to review the contents of the JCL before submitting the job. The idea of a setting.json option has potential too but do we want to add more complexity and things to maintain when few people would even realize it is there.

**Comment by fbeyl** [comment]
You are absolutly right for the majority of users but some of us ( sysprogs, .... ) appreciate a possibility to protect against errors. I wonder if it could be a setting / attribute stored in the favorites section or even in a separate section. That way it can be linked to specific datasets /files that contain delicate jobs, possibly even with a level of confirmation (jobname or content based). A simple popup asking for delicate or not in the create favorite function could do the job.
